#!/bin/bash

echo "✅ Counter Export Fixed - Attributes Instead of Nested Elements"
echo "============================================================="
echo ""
echo "📝 What was fixed:"
echo "  • Counter effects now export as attributes on choice elements"
echo "  • Both dialog tree and movement choices fixed"
echo "  • Emotion removed from all dialog elements"
echo ""
echo "🧪 Test Instructions:"
echo ""
echo "1. Build and start:"
echo "   npm run build && npm run dev"
echo ""
echo "2. Create a dialog tree with counter effects:"
echo "   - Add player choices"
echo "   - Set counter and change values"
echo "   - Export and verify format:"
echo ""
echo "   CORRECT: <choice id=\"1\" text=\"Be brave\" counter=\"courage\" change=\"10\" />"
echo "   WRONG:   <choice id=\"1\" text=\"Be brave\">"
echo "              <counter name=\"courage\" change=\"10\" />"
echo "            </choice>"
echo ""
echo "3. Expected export format:"
echo ""
echo "Dialog Tree:"
echo "<function kind=\"dialogTree\" speaker=\"Old Wizard\" text=\"Choose...\">"
echo "  <choice id=\"1\" text=\"Be brave\" counter=\"courage\" change=\"10\" target=\"7\" />"
echo "  <choice id=\"2\" text=\"Be cautious\" counter=\"courage\" change=\"-5\">"
echo "    <target>"
echo "      <dialogTree id=\"node_123\" speaker=\"Old Wizard\" text=\"Wise...\">"
echo "        <choice id=\"3\" text=\"Continue\" counter=\"wisdom\" change=\"5\" target=\"8\" />"
echo "      </dialogTree>"
echo "    </target>"
echo "  </choice>"
echo "</function>"
echo ""
echo "Movement Choice:"
echo "<function kind=\"movementChoice\" question=\"Where?\">"
echo "  <choice id=\"1\" text=\"Dark path\" counter=\"courage\" change=\"5\" target=\"4\" />"
echo "  <choice id=\"2\" text=\"Safe road\" counter=\"health\" change=\"10\" target=\"5\" />"
echo "</function>"
echo ""
echo "Condition Beat:"
echo "<function kind=\"conditionBeat\">"
echo "  <condition type=\"counter\" operator=\">=\" counter=\"courage\" val=\"60\" />"
echo "  <trueTarget targetBeat=\"7\" />"
echo "  <falseTarget targetBeat=\"8\" />"
echo "</function>"
echo ""
echo "✅ All fixes applied!"