#!/bin/bash

# Make this script executable
chmod +x test-dialog-fixes.sh

echo "🧪 Testing Dialog Tree Editor Fixes"
echo "===================================="
echo ""
echo "✅ All fixes have been applied directly to:"
echo "   packages/builder/src/editors/DialogTreeEditor.tsx"
echo ""
echo "📝 What was fixed:"
echo "  1. ✅ 'Add Player Response' button now shows for new/empty dialog trees"
echo "  2. ✅ Nested NPC editing now works at ALL levels (not just first)"
echo "  3. ✅ Improved expand/collapse logic (root always shows content)"
echo ""
echo "🔧 Building project..."
npm run build

echo ""
echo "🚀 Starting dev server..."
echo ""
echo "📋 TEST CHECKLIST:"
echo "=================="
echo ""
echo "1️⃣ Test New Dialog Tree:"
echo "   • Create a new dialogTree beat"
echo "   • ✓ Should see 'Add Player Response' button immediately"
echo ""
echo "2️⃣ Test Nested Editing:"
echo "   • Add a player choice"
echo "   • Select '➕ Add NPC response...' from dropdown"
echo "   • Click edit icon on the nested NPC"
echo "   • ✓ Edit modal should open with correct values"
echo "   • ✓ Changes should save properly"
echo ""
echo "3️⃣ Test Deep Nesting:"
echo "   • Create: NPC → Player → NPC → Player → NPC"
echo "   • Click edit on the deepest NPC"
echo "   • ✓ Should be able to edit speaker, emotion, and text"
echo ""
echo "4️⃣ Test Collapse/Expand:"
echo "   • Click arrows to collapse individual threads"
echo "   • ✓ Should see 'Has response →' badge when collapsed"
echo "   • Use minimize/maximize button in header"
echo "   • ✓ Root should always show 'Add Player Response'"
echo ""
echo "5️⃣ Test Export:"
echo "   • Create nested dialogs"
echo "   • Export the story"
echo "   • ✓ XML should show proper nested <dialogTree> elements"
echo "   • ✓ No more [object Object] in export"
echo ""

npm run dev