#!/bin/bash

echo "🔧 Testing Nested NPC Edit Button Fix"
echo "====================================="
echo ""
echo "✅ Fix Applied: Nested NPCs now correctly identified as NPC nodes"
echo "   Changed depth increment from +1 to +2 for nested dialogs"
echo ""
echo "📝 What this fixes:"
echo "  • Nested NPC responses now have edit buttons"
echo "  • Depth calculation now correctly alternates NPC/Player"
echo "  • 'Add Player Response' shows for all NPC nodes"
echo ""
echo "🧪 Test Instructions:"
echo "===================="
echo ""
echo "1️⃣ Build and start:"
echo "   npm run build && npm run dev"
echo ""
echo "2️⃣ Create dialog structure:"
echo "   a) Create new dialogTree beat"
echo "   b) Click 'Add Player Response'"
echo "   c) Enter player text: 'Hello there'"
echo "   d) In dropdown, select '➕ Add NPC response...'"
echo "   e) ✓ The new NPC should have an EDIT button"
echo "   f) ✓ The new NPC should show 'Add Player Response' button"
echo ""
echo "3️⃣ Test deep nesting:"
echo "   NPC (depth 0) ✓ has edit"
echo "   └─ Player choice"
echo "      └─ NPC (depth 2) ✓ should have edit"
echo "          └─ Player choice"  
echo "              └─ NPC (depth 4) ✓ should have edit"
echo "                  └─ Player choice"
echo "                      └─ NPC (depth 6) ✓ should have edit"
echo ""
echo "4️⃣ Verify pattern:"
echo "   • Even depths (0,2,4,6...) = NPC with edit button"
echo "   • Odd depths would be player nodes (but we skip odd with +2)"
echo ""
echo "Starting build..."
npm run build

echo ""
echo "✅ Fix complete! Starting dev server..."
npm run dev