/**
 * HTML Exporter - Export stories as standalone HTML files
 *
 * Supports two modes:
 * 1. Folder export: Creates a folder with index.html, player.js, story.asaps.zip, and assets/
 * 2. Single-file export: Creates a single HTML file with all assets inlined as base64
 */

import JSZip from 'jszip';
import { getStorageManager } from '../storage/StorageManager';
import type { StoredAsset } from '../storage/types';

export type AIProvider = 'openai' | 'anthropic' | 'custom' | 'local';

// Template for standalone HTML player
const HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>{{STORY_TITLE}}</title>
  <meta name="description" content="An interactive story created with ASAPS">
  <meta name="author" content="{{STORY_AUTHOR}}">

  <!-- Prevent zooming on mobile -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">

  <!-- Generated by ASAPS Builder - https://asaps.app -->

  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    html, body {
      width: 100%;
      height: 100%;
      overflow: hidden;
      background: #1a1a2e;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    }

    #player {
      width: 100%;
      height: 100%;
    }

    /* Iframe responsive mode */
    .iframe-mode #player {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
    }

    /* Loading state */
    .loading-screen {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 16px;
      color: #fff;
    }

    .spinner {
      width: 48px;
      height: 48px;
      border: 3px solid #4a4a8a;
      border-top-color: #6366f1;
      border-radius: 50%;
      animation: spin 1s linear infinite;
    }

    @keyframes spin {
      to { transform: rotate(360deg); }
    }
  </style>
</head>
<body>
  <div id="player">
    <div class="loading-screen">
      <div class="spinner"></div>
      <div>Loading story...</div>
    </div>
  </div>

  <script>
    // Story configuration
    window.ASAPS_CONFIG = {
      enableAI: {{ENABLE_AI}},
      storyUrl: '{{STORY_URL}}',
      storyData: '{{STORY_DATA}}',
      aiConfig: {{AI_CONFIG}},
    };
  </script>

  <!-- Player bundle -->
  {{PLAYER_SCRIPT}}

  <script>
    (function() {
      // Detect iframe mode
      if (window.parent !== window) {
        document.body.classList.add('iframe-mode');
      }

      // Get story source
      var storySource;
      if (window.ASAPS_CONFIG.storyData) {
        storySource = 'data:application/zip;base64,' + window.ASAPS_CONFIG.storyData;
      } else if (window.ASAPS_CONFIG.storyUrl) {
        storySource = window.ASAPS_CONFIG.storyUrl;
      } else {
        storySource = 'story.asaps.zip';
      }

      // Wait for player to be ready
      if (typeof ASAPSPlayer !== 'undefined') {
        ASAPSPlayer.init('#player', {
          story: storySource,
          enableAI: window.ASAPS_CONFIG.enableAI,
        });
      } else {
        console.error('ASAPS Player not loaded');
      }
    })();
  </script>
</body>
</html>`;

// Template for multi-language HTML player with embedded translations
const MULTI_LANGUAGE_HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>{{STORY_TITLE}}</title>
  <meta name="description" content="An interactive story created with ASAPS">
  <meta name="author" content="{{STORY_AUTHOR}}">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <!-- Generated by ASAPS Builder - https://asaps.app -->
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    html, body { width: 100%; height: 100%; overflow: hidden; background: #1a1a2e; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    #player { width: 100%; height: 100%; }
    .iframe-mode #player { position: absolute; top: 0; left: 0; right: 0; bottom: 0; }
    .loading-screen { position: absolute; top: 0; left: 0; right: 0; bottom: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px; color: #fff; }
    .spinner { width: 48px; height: 48px; border: 3px solid #4a4a8a; border-top-color: #6366f1; border-radius: 50%; animation: spin 1s linear infinite; }
    @keyframes spin { to { transform: rotate(360deg); } }
    .language-selector { position: fixed; top: 12px; right: 12px; z-index: 9999; display: flex; align-items: center; gap: 6px; background: rgba(30, 30, 60, 0.9); border: 1px solid rgba(99, 102, 241, 0.4); border-radius: 8px; padding: 6px 10px; backdrop-filter: blur(8px); }
    .language-selector select { background: transparent; color: #fff; border: none; font-size: 13px; cursor: pointer; outline: none; padding: 2px 4px; }
    .language-selector select option { background: #1a1a2e; color: #fff; }
    .language-selector label { color: rgba(255,255,255,0.7); font-size: 12px; }
  </style>
</head>
<body>
  <div class="language-selector">
    <label>Language:</label>
    <select id="lang-select" onchange="switchLanguage(this.value)">
      <option value="original" selected>Original</option>
      {{LANGUAGE_OPTIONS}}
    </select>
  </div>

  <div id="player">
    <div class="loading-screen">
      <div class="spinner"></div>
      <div>Loading story...</div>
    </div>
  </div>

  <script>
    window.ASAPS_CONFIG = {
      enableAI: {{ENABLE_AI}},
      storyData: '{{ORIGINAL_STORY_DATA}}',
      aiConfig: {{AI_CONFIG}},
    };

    window.ASAPS_TRANSLATIONS = {
{{TRANSLATIONS_MAP}}
    };

    function switchLanguage(lang) {
      var data = lang === 'original'
        ? window.ASAPS_CONFIG.storyData
        : window.ASAPS_TRANSLATIONS[lang];
      if (!data) return;

      var storySource = 'data:application/zip;base64,' + data;

      var playerEl = document.getElementById('player');
      playerEl.innerHTML = '<div class="loading-screen"><div class="spinner"></div><div>Loading story...</div></div>';

      if (typeof ASAPSPlayer !== 'undefined') {
        ASAPSPlayer.init('#player', {
          story: storySource,
          enableAI: window.ASAPS_CONFIG.enableAI,
        });
      }
    }
  </script>

  {{PLAYER_SCRIPT}}

  <script>
    (function() {
      if (window.parent !== window) {
        document.body.classList.add('iframe-mode');
      }
      var storySource = 'data:application/zip;base64,' + window.ASAPS_CONFIG.storyData;
      if (typeof ASAPSPlayer !== 'undefined') {
        ASAPSPlayer.init('#player', {
          story: storySource,
          enableAI: window.ASAPS_CONFIG.enableAI,
        });
      }
    })();
  </script>
</body>
</html>`;

export interface HtmlExportOptions {
  /** Export mode: 'folder' creates separate files, 'single-file' inlines everything */
  mode: 'folder' | 'single-file';
  /** Enable responsive scaling to container */
  responsive: boolean;
  /** Enable AI features (requires API key on playback) */
  enableAI: boolean;
  /** Show API key prompt when AI is needed */
  showApiKeyPrompt: boolean;
  /** AI provider to use (if embedding API key) */
  aiProvider?: AIProvider;
  /** API key to embed (if provided by creator) */
  aiApiKey?: string;
  /** Custom base URL for API (OpenAI-compatible endpoints) */
  aiBaseUrl?: string;
  /** Model override (e.g., 'gpt-5.2', 'claude-sonnet-4-20250514') */
  aiModel?: string;
  /** Languages to translate the story into (AI-powered) */
  translateLanguages?: string[];
  /** How to package translations: separate HTML files or bundled with language switcher */
  translationMode?: 'separate' | 'bundled';
  /** Progress callback for translation */
  onTranslationProgress?: (progress: import('./StoryTranslator').TranslationProgress) => void;
  /** AbortSignal for cancellation */
  signal?: AbortSignal;
}

export interface HtmlExportResult {
  /** For single-file mode: the complete HTML as a string */
  html?: string;
  /** For folder mode: a Blob containing the ZIP of all files */
  zip?: Blob;
  /** Export mode used */
  mode: 'folder' | 'single-file';
}

/**
 * Export project as standalone HTML
 */
export async function exportAsHtml(
  projectId: string,
  options: HtmlExportOptions
): Promise<HtmlExportResult> {
  const storage = getStorageManager();

  // Get project data
  const projectResult = await storage.getProject(projectId);
  if (!projectResult.success || !projectResult.data) {
    throw new Error('Project not found');
  }

  const project = projectResult.data;

  // First, export the project as a playable .asaps.zip
  const storyZipBlob = await createStoryZip(projectId);

  if (options.mode === 'single-file') {
    return exportAsSingleFile(project, storyZipBlob, options);
  } else {
    return exportAsFolder(project, storyZipBlob, options);
  }
}

/**
 * Create story ZIP blob for export (same format as regular export)
 */
async function createStoryZip(projectId: string): Promise<Blob> {
  const { exportProjectAsZip } = await import('../utils/projectZipManager');
  return exportProjectAsZip(projectId);
}

/**
 * Create a story ZIP from in-memory project data (for translated stories).
 * Re-packages the original ZIP but replaces project.json with translated data.
 */
async function createStoryZipFromData(originalZipBlob: Blob, translatedProjectData: any): Promise<Blob> {
  const originalZip = await JSZip.loadAsync(originalZipBlob);

  // Create new ZIP with same structure
  const newZip = new JSZip();

  // Copy all files from original except project.json
  for (const [path, file] of Object.entries(originalZip.files)) {
    if (path === 'project.json') continue;
    if (file.dir) {
      newZip.folder(path);
    } else {
      const content = await file.async('arraybuffer');
      newZip.file(path, content);
    }
  }

  // Add translated project.json
  newZip.file('project.json', JSON.stringify(translatedProjectData, null, 2));

  return newZip.generateAsync({ type: 'blob' });
}

/**
 * Export as a single self-contained HTML file
 */
async function exportAsSingleFile(
  project: any,
  storyZipBlob: Blob,
  options: HtmlExportOptions
): Promise<HtmlExportResult> {
  // Convert story to base64
  const storyArrayBuffer = await storyZipBlob.arrayBuffer();
  const storyBase64 = arrayBufferToBase64(storyArrayBuffer);

  // Get player bundle (would normally be loaded from player-web package)
  // For now, use a placeholder that indicates the player bundle should be included
  const playerScript = await getPlayerScript();

  // Build AI config object (or null if not provided)
  const aiConfig = options.aiProvider && options.aiApiKey
    ? JSON.stringify({
        provider: options.aiProvider,
        apiKey: options.aiApiKey,
        baseUrl: options.aiBaseUrl || undefined,
        model: options.aiModel || undefined,
      })
    : 'null';

  // Build HTML
  const html = HTML_TEMPLATE
    .replace('{{STORY_TITLE}}', escapeHtml(project.name || 'ASAPS Story'))
    .replace('{{STORY_AUTHOR}}', escapeHtml(getAuthor(project)))
    .replace('{{ENABLE_AI}}', String(options.enableAI))
    .replace("'{{STORY_URL}}'", "''")  // Empty for single-file mode
    .replace("'{{STORY_DATA}}'", `'${storyBase64}'`)
    .replace('{{AI_CONFIG}}', aiConfig)
    .replace('{{PLAYER_SCRIPT}}', playerScript);

  return { html, mode: 'single-file' };
}

/**
 * Export as a folder with separate files
 */
async function exportAsFolder(
  project: any,
  storyZipBlob: Blob,
  options: HtmlExportOptions
): Promise<HtmlExportResult> {
  const zip = new JSZip();

  // Get player bundle
  const playerScript = await getPlayerScript();

  // Build AI config object (or null if not provided)
  const aiConfig = options.aiProvider && options.aiApiKey
    ? JSON.stringify({
        provider: options.aiProvider,
        apiKey: options.aiApiKey,
        baseUrl: options.aiBaseUrl || undefined,
        model: options.aiModel || undefined,
      })
    : 'null';

  // Build HTML that references external story file
  const html = HTML_TEMPLATE
    .replace('{{STORY_TITLE}}', escapeHtml(project.name || 'ASAPS Story'))
    .replace('{{STORY_AUTHOR}}', escapeHtml(getAuthor(project)))
    .replace('{{ENABLE_AI}}', String(options.enableAI))
    .replace("'{{STORY_URL}}'", "'story.asaps.zip'")
    .replace("'{{STORY_DATA}}'", "''")  // Empty for folder mode
    .replace('{{AI_CONFIG}}', aiConfig)
    .replace('{{PLAYER_SCRIPT}}', playerScript);

  // Add files to ZIP
  zip.file('index.html', html);
  zip.file('story.asaps.zip', storyZipBlob);

  // Generate ZIP
  const zipBlob = await zip.generateAsync({ type: 'blob' });

  return { zip: zipBlob, mode: 'folder' };
}

/**
 * Get the player script and CSS bundle
 * Loads the pre-built player-web bundle from public folder
 * Uses base64 data URL to avoid any HTML escaping issues
 */
async function getPlayerScript(): Promise<string> {
  // Try multiple paths to load the player bundle
  const jsPaths = [
    '/player-web.js',      // Development (Vite dev server)
    './player-web.js',     // Relative path
    'player-web.js',       // Same folder
  ];

  const cssPaths = [
    '/player-web.css',      // Development (Vite dev server)
    './player-web.css',     // Relative path
    'player-web.css',       // Same folder
  ];

  let scriptTag = '';
  let styleTag = '';

  // Load JavaScript bundle
  for (const path of jsPaths) {
    try {
      const response = await fetch(path);
      if (response.ok) {
        const script = await response.text();
        console.log('[HtmlExporter] Loaded player bundle from:', path, 'size:', script.length);

        // Encode as base64 data URL to avoid any HTML escaping issues
        const base64Script = btoa(unescape(encodeURIComponent(script)));
        scriptTag = `<script src="data:text/javascript;base64,${base64Script}"></script>`;
        break;
      }
    } catch (e) {
      // Try next path
    }
  }

  // Load CSS bundle
  for (const path of cssPaths) {
    try {
      const response = await fetch(path);
      if (response.ok) {
        const css = await response.text();
        console.log('[HtmlExporter] Loaded player CSS from:', path, 'size:', css.length);

        // Encode as base64 data URL to avoid any HTML escaping issues
        const base64Css = btoa(unescape(encodeURIComponent(css)));
        styleTag = `<link rel="stylesheet" href="data:text/css;base64,${base64Css}">`;
        break;
      }
    } catch (e) {
      // Try next path
    }
  }

  if (scriptTag) {
    return `${styleTag}\n  ${scriptTag}`;
  }

  console.error('[HtmlExporter] Could not load player-web bundle from any path');

  // Fallback: Show error with instructions
  return `<script>
// ASAPS Player Web - Bundle not found
(function() {
  window.ASAPSPlayer = {
    init: function(container, options) {
      var el = typeof container === 'string' ? document.querySelector(container) : container;
      if (!el) return;
      el.innerHTML = '<div style="display:flex;align-items:center;justify-content:center;height:100%;color:#fff;text-align:center;padding:20px;font-family:system-ui,sans-serif;">' +
        '<div>' +
        '<div style="width:64px;height:64px;background:#ff6b6b;color:white;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:32px;font-weight:bold;margin:0 auto 20px;">!</div>' +
        '<h2 style="margin-bottom:16px;">Player Bundle Missing</h2>' +
        '<p style="color:#888;margin-bottom:16px;max-width:400px;">The player-web bundle was not found. This is likely a build issue.</p>' +
        '<p style="color:#666;font-size:14px;">Run: npm run build -w @asaps/player-web</p>' +
        '</div></div>';
    }
  };
})();
</script>`;
}

/**
 * Helper: Convert ArrayBuffer to base64
 */
function arrayBufferToBase64(buffer: ArrayBuffer): string {
  let binary = '';
  const bytes = new Uint8Array(buffer);
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

/**
 * Helper: Escape HTML special characters
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Helper: Get author from project
 */
function getAuthor(project: any): string {
  if (project.story?.metadata?.author) {
    return project.story.metadata.author;
  }
  if (project.globalSettings?.author) {
    return project.globalSettings.author;
  }
  return 'ASAPS Creator';
}

/**
 * Download HTML export to user's computer
 */
export async function downloadHtmlExport(
  projectId: string,
  projectName: string,
  options: HtmlExportOptions
): Promise<void> {
  const safeName = projectName.replace(/[^a-z0-9]/gi, '_');
  const hasTranslations = options.translateLanguages && options.translateLanguages.length > 0;

  if (!hasTranslations) {
    // Standard export (no translations)
    const result = await exportAsHtml(projectId, options);
    if (result.mode === 'single-file' && result.html) {
      const blob = new Blob([result.html], { type: 'text/html' });
      downloadBlob(blob, `${safeName}.html`);
    } else if (result.mode === 'folder' && result.zip) {
      downloadBlob(result.zip, `${safeName}_html.zip`);
    }
    return;
  }

  // Translation export
  const { translateStory } = await import('./StoryTranslator');
  const { exportProjectAsZip, getProjectDataForExport } = await import('../utils/projectZipManager');

  const languages = options.translateLanguages!;
  const translationMode = options.translationMode || 'separate';

  // Get the original story ZIP and project data
  const originalZipBlob = await exportProjectAsZip(projectId);
  const projectData = await getProjectDataForExport(projectId);

  const aiConfig = {
    provider: options.aiProvider || 'openai' as AIProvider,
    apiKey: options.aiApiKey,
    baseUrl: options.aiBaseUrl,
    model: options.aiModel,
  };

  console.log(`[HtmlExporter] Starting translation for ${languages.length} languages`);

  // Translate for each language
  const translatedResults: Array<{ language: string; projectData: any; zipBlob: Blob }> = [];

  for (let i = 0; i < languages.length; i++) {
    const language = languages[i];
    console.log(`[HtmlExporter] Translating language ${i + 1}/${languages.length}: ${language}`);

    const translated = await translateStory(
      projectData,
      language,
      aiConfig,
      (progress) => {
        options.onTranslationProgress?.({
          ...progress,
          languageIndex: i,
          totalLanguages: languages.length,
        });
      },
      options.signal
    );

    console.log(`[HtmlExporter] Building ZIP for ${language}...`);
    const translatedZip = await createStoryZipFromData(originalZipBlob, translated);
    console.log(`[HtmlExporter] ZIP for ${language} done, size: ${translatedZip.size}`);
    translatedResults.push({ language, projectData: translated, zipBlob: translatedZip });
  }

  // Signal packaging phase (language count + 1 as a "packaging" indicator)
  options.onTranslationProgress?.({
    currentLanguage: 'Packaging files...',
    languageIndex: languages.length,
    totalLanguages: languages.length,
    stringsTranslated: 0,
    totalStrings: 0,
  });

  console.log('[HtmlExporter] All translations done, packaging export...');

  // Get player bundle and AI config for HTML generation
  const playerScript = await getPlayerScript();
  const htmlAiConfig = options.aiProvider && options.aiApiKey
    ? JSON.stringify({
        provider: options.aiProvider,
        apiKey: options.aiApiKey,
        baseUrl: options.aiBaseUrl || undefined,
        model: options.aiModel || undefined,
      })
    : 'null';

  const storage = getStorageManager();
  const projectResult = await storage.getProject(projectId);
  const project = projectResult.data!;

  if (translationMode === 'separate') {
    // Separate files mode: ZIP with one HTML per language
    console.log('[HtmlExporter] Building separate-files ZIP...');
    const outerZip = new JSZip();

    // Add original language export
    if (options.mode === 'single-file') {
      const origBase64 = arrayBufferToBase64(await originalZipBlob.arrayBuffer());
      const origHtml = buildHtml(project, origBase64, '', playerScript, htmlAiConfig, options);
      outerZip.file(`${safeName}.html`, origHtml);
    } else {
      const origHtml = buildHtml(project, '', 'story.asaps.zip', playerScript, htmlAiConfig, options);
      const folder = outerZip.folder(safeName)!;
      folder.file('index.html', origHtml);
      folder.file('story.asaps.zip', originalZipBlob);
    }

    // Add translated exports
    for (const { language, zipBlob } of translatedResults) {
      const langSuffix = language.toLowerCase().replace(/\s+/g, '_');
      console.log(`[HtmlExporter] Adding ${language} to ZIP...`);

      if (options.mode === 'single-file') {
        const base64 = arrayBufferToBase64(await zipBlob.arrayBuffer());
        const html = buildHtml(project, base64, '', playerScript, htmlAiConfig, options, language);
        outerZip.file(`${safeName}_${langSuffix}.html`, html);
      } else {
        const folderName = `${safeName}_${langSuffix}`;
        const folder = outerZip.folder(folderName)!;
        const html = buildHtml(project, '', 'story.asaps.zip', playerScript, htmlAiConfig, options, language);
        folder.file('index.html', html);
        folder.file('story.asaps.zip', zipBlob);
      }
    }

    console.log('[HtmlExporter] Generating final ZIP...');
    const zipBlob = await outerZip.generateAsync({ type: 'blob' });
    console.log(`[HtmlExporter] Final ZIP size: ${zipBlob.size}, downloading...`);
    downloadBlob(zipBlob, `${safeName}_translated.zip`);

  } else {
    // Bundled mode: single HTML with all translations embedded + language selector
    console.log('[HtmlExporter] Building bundled multi-language HTML...');
    const originalBase64 = arrayBufferToBase64(await originalZipBlob.arrayBuffer());

    const translationEntries: Array<{ language: string; base64: string }> = [];
    for (const { language, zipBlob } of translatedResults) {
      const base64 = arrayBufferToBase64(await zipBlob.arrayBuffer());
      translationEntries.push({ language, base64 });
    }

    const html = buildMultiLanguageHtml(
      project,
      originalBase64,
      translationEntries,
      playerScript,
      htmlAiConfig,
      options
    );

    console.log(`[HtmlExporter] Bundled HTML size: ${html.length}, downloading...`);
    const blob = new Blob([html], { type: 'text/html' });
    downloadBlob(blob, `${safeName}.html`);
  }

  console.log('[HtmlExporter] Export complete!');
}

/**
 * Build an HTML string from template parts.
 * Used by both standard export and translated exports.
 */
function buildHtml(
  project: any,
  storyBase64: string,
  storyUrl: string,
  playerScript: string,
  aiConfig: string,
  options: HtmlExportOptions,
  language?: string
): string {
  const title = language
    ? `${project.name || 'ASAPS Story'} (${language})`
    : (project.name || 'ASAPS Story');

  return HTML_TEMPLATE
    .replace('{{STORY_TITLE}}', escapeHtml(title))
    .replace('{{STORY_AUTHOR}}', escapeHtml(getAuthor(project)))
    .replace('{{ENABLE_AI}}', String(options.enableAI))
    .replace("'{{STORY_URL}}'", storyUrl ? `'${storyUrl}'` : "''")
    .replace("'{{STORY_DATA}}'", storyBase64 ? `'${storyBase64}'` : "''")
    .replace('{{AI_CONFIG}}', aiConfig)
    .replace('{{PLAYER_SCRIPT}}', playerScript);
}

/**
 * Build a multi-language HTML file with all translations embedded and a language selector.
 */
function buildMultiLanguageHtml(
  project: any,
  originalBase64: string,
  translations: Array<{ language: string; base64: string }>,
  playerScript: string,
  aiConfig: string,
  options: HtmlExportOptions
): string {
  // Build the translations map JavaScript
  const translationsJs = translations
    .map(t => `    ${JSON.stringify(t.language)}: '${t.base64}'`)
    .join(',\n');

  return MULTI_LANGUAGE_HTML_TEMPLATE
    .replace('{{STORY_TITLE}}', escapeHtml(project.name || 'ASAPS Story'))
    .replace('{{STORY_AUTHOR}}', escapeHtml(getAuthor(project)))
    .replace('{{ENABLE_AI}}', String(options.enableAI))
    .replace("'{{ORIGINAL_STORY_DATA}}'", `'${originalBase64}'`)
    .replace('{{AI_CONFIG}}', aiConfig)
    .replace('{{TRANSLATIONS_MAP}}', translationsJs)
    .replace('{{LANGUAGE_OPTIONS}}', translations
      .map(t => `<option value="${escapeHtml(t.language)}">${escapeHtml(t.language)}</option>`)
      .join('\n          '))
    .replace('{{PLAYER_SCRIPT}}', playerScript);
}

/**
 * Helper: Download blob as file
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
