/**
 * HTML Exporter - Export stories as standalone HTML files
 *
 * Supports two modes:
 * 1. Folder export: Creates a folder with index.html, player.js, story.asaps.zip, and assets/
 * 2. Single-file export: Creates a single HTML file with all assets inlined as base64
 */

import JSZip from 'jszip';
import { getStorageManager } from '../storage/StorageManager';
import type { StoredAsset } from '../storage/types';

export type AIProvider = 'openai' | 'anthropic' | 'custom' | 'local';

// Template for standalone HTML player
const HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>{{STORY_TITLE}}</title>
  <meta name="description" content="An interactive story created with ASAPS">
  <meta name="author" content="{{STORY_AUTHOR}}">

  <!-- Prevent zooming on mobile -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">

  <!-- Generated by ASAPS Builder - https://asaps.app -->

  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    html, body {
      width: 100%;
      height: 100%;
      overflow: hidden;
      background: #1a1a2e;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    }

    #player {
      width: 100%;
      height: 100%;
    }

    /* Iframe responsive mode */
    .iframe-mode #player {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
    }

    /* Loading state */
    .loading-screen {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 16px;
      color: #fff;
    }

    .spinner {
      width: 48px;
      height: 48px;
      border: 3px solid #4a4a8a;
      border-top-color: #6366f1;
      border-radius: 50%;
      animation: spin 1s linear infinite;
    }

    @keyframes spin {
      to { transform: rotate(360deg); }
    }
  </style>
</head>
<body>
  <div id="player">
    <div class="loading-screen">
      <div class="spinner"></div>
      <div>Loading story...</div>
    </div>
  </div>

  <script>
    // Story configuration
    window.ASAPS_CONFIG = {
      enableAI: {{ENABLE_AI}},
      storyUrl: '{{STORY_URL}}',
      storyData: '{{STORY_DATA}}',
      aiConfig: {{AI_CONFIG}},
    };
  </script>

  <!-- Player bundle -->
  {{PLAYER_SCRIPT}}

  <script>
    (function() {
      // Detect iframe mode
      if (window.parent !== window) {
        document.body.classList.add('iframe-mode');
      }

      // Get story source
      var storySource;
      if (window.ASAPS_CONFIG.storyData) {
        storySource = 'data:application/zip;base64,' + window.ASAPS_CONFIG.storyData;
      } else if (window.ASAPS_CONFIG.storyUrl) {
        storySource = window.ASAPS_CONFIG.storyUrl;
      } else {
        storySource = 'story.asaps.zip';
      }

      // Wait for player to be ready
      if (typeof ASAPSPlayer !== 'undefined') {
        ASAPSPlayer.init('#player', {
          story: storySource,
          enableAI: window.ASAPS_CONFIG.enableAI,
        });
      } else {
        console.error('ASAPS Player not loaded');
      }
    })();
  </script>
</body>
</html>`;

export interface HtmlExportOptions {
  /** Export mode: 'folder' creates separate files, 'single-file' inlines everything */
  mode: 'folder' | 'single-file';
  /** Enable responsive scaling to container */
  responsive: boolean;
  /** Enable AI features (requires API key on playback) */
  enableAI: boolean;
  /** Show API key prompt when AI is needed */
  showApiKeyPrompt: boolean;
  /** AI provider to use (if embedding API key) */
  aiProvider?: AIProvider;
  /** API key to embed (if provided by creator) */
  aiApiKey?: string;
  /** Custom base URL for API (OpenAI-compatible endpoints) */
  aiBaseUrl?: string;
  /** Model override (e.g., 'gpt-5.2', 'claude-sonnet-4-20250514') */
  aiModel?: string;
  /** Languages to translate the story into (AI-powered) */
  translateLanguages?: string[];
}

export interface HtmlExportResult {
  /** For single-file mode: the complete HTML as a string */
  html?: string;
  /** For folder mode: a Blob containing the ZIP of all files */
  zip?: Blob;
  /** Export mode used */
  mode: 'folder' | 'single-file';
}

/**
 * Export project as standalone HTML
 */
export async function exportAsHtml(
  projectId: string,
  options: HtmlExportOptions
): Promise<HtmlExportResult> {
  const storage = getStorageManager();

  // Get project data
  const projectResult = await storage.getProject(projectId);
  if (!projectResult.success || !projectResult.data) {
    throw new Error('Project not found');
  }

  const project = projectResult.data;

  // First, export the project as a playable .asaps.zip
  const storyZipBlob = await createStoryZip(projectId);

  if (options.mode === 'single-file') {
    return exportAsSingleFile(project, storyZipBlob, options);
  } else {
    return exportAsFolder(project, storyZipBlob, options);
  }
}

/**
 * Create story ZIP blob for export (same format as regular export)
 */
async function createStoryZip(projectId: string): Promise<Blob> {
  const { exportProjectAsZip } = await import('../utils/projectZipManager');
  return exportProjectAsZip(projectId);
}

/**
 * Export as a single self-contained HTML file
 */
async function exportAsSingleFile(
  project: any,
  storyZipBlob: Blob,
  options: HtmlExportOptions
): Promise<HtmlExportResult> {
  // Convert story to base64
  const storyArrayBuffer = await storyZipBlob.arrayBuffer();
  const storyBase64 = arrayBufferToBase64(storyArrayBuffer);

  // Get player bundle (would normally be loaded from player-web package)
  // For now, use a placeholder that indicates the player bundle should be included
  const playerScript = await getPlayerScript();

  // Build AI config object (or null if not provided)
  const aiConfig = options.aiProvider && options.aiApiKey
    ? JSON.stringify({
        provider: options.aiProvider,
        apiKey: options.aiApiKey,
        baseUrl: options.aiBaseUrl || undefined,
        model: options.aiModel || undefined,
      })
    : 'null';

  // Build HTML
  const html = HTML_TEMPLATE
    .replace('{{STORY_TITLE}}', escapeHtml(project.name || 'ASAPS Story'))
    .replace('{{STORY_AUTHOR}}', escapeHtml(getAuthor(project)))
    .replace('{{ENABLE_AI}}', String(options.enableAI))
    .replace("'{{STORY_URL}}'", "''")  // Empty for single-file mode
    .replace("'{{STORY_DATA}}'", `'${storyBase64}'`)
    .replace('{{AI_CONFIG}}', aiConfig)
    .replace('{{PLAYER_SCRIPT}}', playerScript);

  return { html, mode: 'single-file' };
}

/**
 * Export as a folder with separate files
 */
async function exportAsFolder(
  project: any,
  storyZipBlob: Blob,
  options: HtmlExportOptions
): Promise<HtmlExportResult> {
  const zip = new JSZip();

  // Get player bundle
  const playerScript = await getPlayerScript();

  // Build AI config object (or null if not provided)
  const aiConfig = options.aiProvider && options.aiApiKey
    ? JSON.stringify({
        provider: options.aiProvider,
        apiKey: options.aiApiKey,
        baseUrl: options.aiBaseUrl || undefined,
        model: options.aiModel || undefined,
      })
    : 'null';

  // Build HTML that references external story file
  const html = HTML_TEMPLATE
    .replace('{{STORY_TITLE}}', escapeHtml(project.name || 'ASAPS Story'))
    .replace('{{STORY_AUTHOR}}', escapeHtml(getAuthor(project)))
    .replace('{{ENABLE_AI}}', String(options.enableAI))
    .replace("'{{STORY_URL}}'", "'story.asaps.zip'")
    .replace("'{{STORY_DATA}}'", "''")  // Empty for folder mode
    .replace('{{AI_CONFIG}}', aiConfig)
    .replace('{{PLAYER_SCRIPT}}', playerScript);

  // Add files to ZIP
  zip.file('index.html', html);
  zip.file('story.asaps.zip', storyZipBlob);

  // Generate ZIP
  const zipBlob = await zip.generateAsync({ type: 'blob' });

  return { zip: zipBlob, mode: 'folder' };
}

/**
 * Get the player script and CSS bundle
 * Loads the pre-built player-web bundle from public folder
 * Uses base64 data URL to avoid any HTML escaping issues
 */
async function getPlayerScript(): Promise<string> {
  // Try multiple paths to load the player bundle
  const jsPaths = [
    '/player-web.js',      // Development (Vite dev server)
    './player-web.js',     // Relative path
    'player-web.js',       // Same folder
  ];

  const cssPaths = [
    '/player-web.css',      // Development (Vite dev server)
    './player-web.css',     // Relative path
    'player-web.css',       // Same folder
  ];

  let scriptTag = '';
  let styleTag = '';

  // Load JavaScript bundle
  for (const path of jsPaths) {
    try {
      const response = await fetch(path);
      if (response.ok) {
        const script = await response.text();
        console.log('[HtmlExporter] Loaded player bundle from:', path, 'size:', script.length);

        // Encode as base64 data URL to avoid any HTML escaping issues
        const base64Script = btoa(unescape(encodeURIComponent(script)));
        scriptTag = `<script src="data:text/javascript;base64,${base64Script}"></script>`;
        break;
      }
    } catch (e) {
      // Try next path
    }
  }

  // Load CSS bundle
  for (const path of cssPaths) {
    try {
      const response = await fetch(path);
      if (response.ok) {
        const css = await response.text();
        console.log('[HtmlExporter] Loaded player CSS from:', path, 'size:', css.length);

        // Encode as base64 data URL to avoid any HTML escaping issues
        const base64Css = btoa(unescape(encodeURIComponent(css)));
        styleTag = `<link rel="stylesheet" href="data:text/css;base64,${base64Css}">`;
        break;
      }
    } catch (e) {
      // Try next path
    }
  }

  if (scriptTag) {
    return `${styleTag}\n  ${scriptTag}`;
  }

  console.error('[HtmlExporter] Could not load player-web bundle from any path');

  // Fallback: Show error with instructions
  return `<script>
// ASAPS Player Web - Bundle not found
(function() {
  window.ASAPSPlayer = {
    init: function(container, options) {
      var el = typeof container === 'string' ? document.querySelector(container) : container;
      if (!el) return;
      el.innerHTML = '<div style="display:flex;align-items:center;justify-content:center;height:100%;color:#fff;text-align:center;padding:20px;font-family:system-ui,sans-serif;">' +
        '<div>' +
        '<div style="width:64px;height:64px;background:#ff6b6b;color:white;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:32px;font-weight:bold;margin:0 auto 20px;">!</div>' +
        '<h2 style="margin-bottom:16px;">Player Bundle Missing</h2>' +
        '<p style="color:#888;margin-bottom:16px;max-width:400px;">The player-web bundle was not found. This is likely a build issue.</p>' +
        '<p style="color:#666;font-size:14px;">Run: npm run build -w @asaps/player-web</p>' +
        '</div></div>';
    }
  };
})();
</script>`;
}

/**
 * Helper: Convert ArrayBuffer to base64
 */
function arrayBufferToBase64(buffer: ArrayBuffer): string {
  let binary = '';
  const bytes = new Uint8Array(buffer);
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

/**
 * Helper: Escape HTML special characters
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Helper: Get author from project
 */
function getAuthor(project: any): string {
  if (project.story?.metadata?.author) {
    return project.story.metadata.author;
  }
  if (project.globalSettings?.author) {
    return project.globalSettings.author;
  }
  return 'ASAPS Creator';
}

/**
 * Download HTML export to user's computer
 */
export async function downloadHtmlExport(
  projectId: string,
  projectName: string,
  options: HtmlExportOptions
): Promise<void> {
  const result = await exportAsHtml(projectId, options);
  const safeName = projectName.replace(/[^a-z0-9]/gi, '_');

  if (result.mode === 'single-file' && result.html) {
    // Download as HTML file
    const blob = new Blob([result.html], { type: 'text/html' });
    downloadBlob(blob, `${safeName}.html`);
  } else if (result.mode === 'folder' && result.zip) {
    // Download as ZIP file
    downloadBlob(result.zip, `${safeName}_html.zip`);
  }
}

/**
 * Helper: Download blob as file
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
