/**
 * HTML Exporter - Export stories as standalone HTML files
 *
 * Supports two modes:
 * 1. Folder export: Creates a folder with index.html, player.js, story.asaps.zip, and assets/
 * 2. Single-file export: Creates a single HTML file with all assets inlined as base64
 *
 * Translation support:
 * - Pre-made translations: bundled as translated ZIP blobs with language selector
 * - AI on-the-fly: embedded script for runtime AI translation in the browser
 */

import JSZip from 'jszip';
import { getStorageManager } from '../storage/StorageManager';
import type { TranslationResource } from '@asaps/core';
import { applyTranslationResource } from './StoryTranslator';
import { downloadAndInlineFonts } from './fontBundler';

export type AIProvider = 'openai' | 'anthropic' | 'custom' | 'local';

// Template for standalone HTML player (no translations)
const HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>{{STORY_TITLE}}</title>
  <meta name="description" content="An interactive story created with ASAPS">
  <meta name="author" content="{{STORY_AUTHOR}}">

  <!-- Prevent zooming on mobile -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">

  <!-- Generated by ASAPS Builder - https://asaps.app -->

  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    html, body {
      width: 100%;
      height: 100%;
      overflow: hidden;
      background: #1a1a2e;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    }

    #player {
      width: 100%;
      height: 100%;
    }

    /* Iframe responsive mode */
    .iframe-mode #player {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
    }

    /* Loading state */
    .loading-screen {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 16px;
      color: #fff;
    }

    .spinner {
      width: 48px;
      height: 48px;
      border: 3px solid #4a4a8a;
      border-top-color: #6366f1;
      border-radius: 50%;
      animation: spin 1s linear infinite;
    }

    @keyframes spin {
      to { transform: rotate(360deg); }
    }
  </style>
</head>
<body>
  <div id="player">
    <div class="loading-screen">
      <div class="spinner"></div>
      <div>Loading story...</div>
    </div>
  </div>

  <script>
    // Mobile device detection
    window.ASAPS_MOBILE = (function() {
      // URL override for testing: append ?mobile=1 to force mobile mode
      try { if (new URLSearchParams(window.location.search).get('mobile') === '1') return true; } catch(e) {}
      var hasTouch = 'ontouchstart' in window || navigator.maxTouchPoints > 0;
      var smallScreen = Math.min(screen.width, screen.height) <= 768;
      var smallViewport = Math.min(window.innerWidth, window.innerHeight) <= 768;
      var mobileUA = /Android|iPhone|iPad|iPod|webOS|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
      // Real device: touch + (small screen OR mobile UA)
      // DevTools sim: touch + small viewport
      return (hasTouch && (smallScreen || mobileUA)) || (hasTouch && smallViewport);
    })();
    console.log('[ASAPS] Mobile:', window.ASAPS_MOBILE, '| touch:', ('ontouchstart' in window || navigator.maxTouchPoints > 0), '| screen:', screen.width + 'x' + screen.height, '| viewport:', window.innerWidth + 'x' + window.innerHeight);

    // Story configuration
    window.ASAPS_CONFIG = {
      enableAI: {{ENABLE_AI}},
      storyUrl: '{{STORY_URL}}',
      storyData: '{{STORY_DATA}}',
      aiConfig: {{AI_CONFIG}},
      ttsConfig: {{TTS_CONFIG}},
      mobileScalingMode: '{{MOBILE_SCALING_MODE}}',
      mobileFontScale: {{MOBILE_FONT_SCALE}},
    };
  </script>

  <!-- Player bundle -->
  {{PLAYER_SCRIPT}}

  <script>
    (function() {
      // Detect iframe mode
      if (window.parent !== window) {
        document.body.classList.add('iframe-mode');
      }

      // Determine mobile mode based on project settings and device detection
      // Cover mode only activates when explicitly chosen (never for 'auto')
      var mobileScaling = window.ASAPS_CONFIG.mobileScalingMode || 'auto';
      var mobileMode = (mobileScaling === 'cover') && !!window.ASAPS_MOBILE;
      // Font scale is independent of cover mode: active on mobile for 'auto' and 'cover'
      var effectiveFontScale = ((mobileScaling === 'auto' || mobileScaling === 'cover') && window.ASAPS_MOBILE)
        ? window.ASAPS_CONFIG.mobileFontScale : 1.0;

      // Get story source
      var storySource;
      if (window.ASAPS_CONFIG.storyData) {
        storySource = 'data:application/zip;base64,' + window.ASAPS_CONFIG.storyData;
      } else if (window.ASAPS_CONFIG.storyUrl) {
        storySource = window.ASAPS_CONFIG.storyUrl;
      } else {
        storySource = 'story.asaps.zip';
      }

      // Wait for player to be ready
      if (typeof ASAPSPlayer !== 'undefined') {
        ASAPSPlayer.init('#player', {
          story: storySource,
          enableAI: window.ASAPS_CONFIG.enableAI,
          mobileMode: mobileMode,
          mobileFontScale: effectiveFontScale,
        });
      } else {
        console.error('ASAPS Player not loaded');
      }
    })();
  </script>
</body>
</html>`;

// Enhanced template for multi-language HTML player with pre-made translations + optional AI on-the-fly
const ENHANCED_MULTI_LANGUAGE_TEMPLATE = `<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>{{STORY_TITLE}}</title>
  <meta name="description" content="An interactive story created with ASAPS">
  <meta name="author" content="{{STORY_AUTHOR}}">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <!-- Generated by ASAPS Builder - https://asaps.app -->

  {{EMBEDDED_FONTS}}

  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    html, body { width: 100%; height: 100%; overflow: hidden; background: #1a1a2e; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    #player { width: 100%; height: 100%; }
    .iframe-mode #player { position: absolute; top: 0; left: 0; right: 0; bottom: 0; }
    .loading-screen { position: absolute; top: 0; left: 0; right: 0; bottom: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px; color: #fff; }
    .spinner { width: 48px; height: 48px; border: 3px solid #4a4a8a; border-top-color: #6366f1; border-radius: 50%; animation: spin 1s linear infinite; }
    @keyframes spin { to { transform: rotate(360deg); } }

    /* Language selector overlay */
    .language-panel {
      position: fixed; top: 12px; right: 12px; z-index: 9999;
      background: rgba(30, 30, 60, 0.92); border: 1px solid rgba(99, 102, 241, 0.4);
      border-radius: 10px; backdrop-filter: blur(8px);
      display: flex; flex-direction: column; transition: all 0.2s ease;
    }
    .language-panel.expanded { padding: 10px 14px; gap: 8px; min-width: 220px; }
    .language-panel.collapsed { padding: 6px; min-width: auto; cursor: pointer; }
    .language-panel .lang-toggle {
      background: none; border: none; color: rgba(255,255,255,0.8); cursor: pointer;
      font-size: 16px; padding: 2px 4px; display: flex; align-items: center; gap: 6px;
    }
    .language-panel .lang-toggle:hover { color: #fff; }
    .language-panel .lang-content { display: flex; flex-direction: column; gap: 8px; }
    .language-panel.collapsed .lang-content { display: none; }
    .language-panel .lang-row { display: flex; align-items: center; gap: 6px; }
    .language-panel label { color: rgba(255,255,255,0.7); font-size: 12px; white-space: nowrap; }
    .language-panel select {
      background: rgba(255,255,255,0.08); color: #fff; border: 1px solid rgba(255,255,255,0.15);
      border-radius: 6px; font-size: 13px; cursor: pointer; outline: none; padding: 4px 8px; flex: 1;
    }
    .language-panel select option { background: #1a1a2e; color: #fff; }
    .language-panel .ai-section { border-top: 1px solid rgba(255,255,255,0.1); padding-top: 8px; }
    .language-panel .ai-row { display: flex; align-items: center; gap: 6px; }
    .language-panel .ai-input {
      background: rgba(255,255,255,0.08); color: #fff; border: 1px solid rgba(255,255,255,0.15);
      border-radius: 6px; font-size: 12px; padding: 4px 8px; flex: 1; outline: none;
    }
    .language-panel .ai-input::placeholder { color: rgba(255,255,255,0.35); }
    .language-panel .ai-btn {
      background: rgba(99, 102, 241, 0.7); color: #fff; border: none; border-radius: 6px;
      font-size: 12px; padding: 4px 10px; cursor: pointer; white-space: nowrap;
    }
    .language-panel .ai-btn:hover { background: rgba(99, 102, 241, 0.9); }
    .language-panel .ai-btn:disabled { opacity: 0.5; cursor: not-allowed; }
    .language-panel .ai-disclaimer {
      color: rgba(255,255,255,0.4); font-size: 10px; line-height: 1.3;
    }
    .language-panel .ai-progress {
      color: rgba(255,255,255,0.6); font-size: 11px;
    }
    .language-panel .ai-error {
      color: #f87171; font-size: 11px;
    }
  </style>
</head>
<body>
  <div class="language-panel expanded" id="lang-panel">
    <button class="lang-toggle" id="lang-toggle" title="Toggle language panel">
      &#127760; <span id="lang-toggle-label">Language</span>
    </button>
    <div class="lang-content">
      <div class="lang-row">
        <label>Language:</label>
        <select id="lang-select">
          <option value="original" selected>Original</option>
          {{LANGUAGE_OPTIONS}}
        </select>
      </div>
      {{AI_TRANSLATION_SECTION}}
    </div>
  </div>
  <script>
    (function() {
      var panel = document.getElementById('lang-panel');
      var toggle = document.getElementById('lang-toggle');
      var label = document.getElementById('lang-toggle-label');
      toggle.addEventListener('click', function() {
        var isExpanded = panel.classList.contains('expanded');
        panel.classList.toggle('expanded');
        panel.classList.toggle('collapsed');
        label.textContent = isExpanded ? '' : 'Language';
      });
    })();
  </script>

  <div id="player">
    <div class="loading-screen">
      <div class="spinner"></div>
      <div>Loading story...</div>
    </div>
  </div>

  <script>
    // Mobile device detection
    window.ASAPS_MOBILE = (function() {
      // URL override for testing: append ?mobile=1 to force mobile mode
      try { if (new URLSearchParams(window.location.search).get('mobile') === '1') return true; } catch(e) {}
      var hasTouch = 'ontouchstart' in window || navigator.maxTouchPoints > 0;
      var smallScreen = Math.min(screen.width, screen.height) <= 768;
      var smallViewport = Math.min(window.innerWidth, window.innerHeight) <= 768;
      var mobileUA = /Android|iPhone|iPad|iPod|webOS|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
      // Real device: touch + (small screen OR mobile UA)
      // DevTools sim: touch + small viewport
      return (hasTouch && (smallScreen || mobileUA)) || (hasTouch && smallViewport);
    })();
    console.log('[ASAPS] Mobile:', window.ASAPS_MOBILE, '| touch:', ('ontouchstart' in window || navigator.maxTouchPoints > 0), '| screen:', screen.width + 'x' + screen.height, '| viewport:', window.innerWidth + 'x' + window.innerHeight);

    window.ASAPS_CONFIG = {
      enableAI: {{ENABLE_AI}},
      storyData: '{{ORIGINAL_STORY_DATA}}',
      aiConfig: {{AI_CONFIG}},
      ttsConfig: {{TTS_CONFIG}},
      mobileScalingMode: '{{MOBILE_SCALING_MODE}}',
      mobileFontScale: {{MOBILE_FONT_SCALE}},
    };

    window.ASAPS_TRANSLATIONS = {
{{TRANSLATIONS_MAP}}
    };

    window.ASAPS_RTL_LANGUAGES = {{RTL_LANGUAGES}};

    // --- Language switching ---
    (function() {
      var langSelect = document.getElementById('lang-select');
      // Track current player instance for proper cleanup
      window._asapsPlayerInstance = null;

      langSelect.addEventListener('change', function() {
        switchToLanguage(this.value);
      });

      // Destroy the current player instance and clean up all audio
      function destroyCurrentPlayer() {
        // 1. Call the player's own destroy method (unmounts React, triggers dispose)
        if (window._asapsPlayerInstance && typeof window._asapsPlayerInstance.destroy === 'function') {
          try { window._asapsPlayerInstance.destroy(); } catch(e) {}
          window._asapsPlayerInstance = null;
        }

        // 2. Safety net: pause and remove any lingering <audio>/<video> elements
        var mediaEls = document.querySelectorAll('audio, video');
        for (var i = 0; i < mediaEls.length; i++) {
          try {
            mediaEls[i].pause();
            mediaEls[i].src = '';
            mediaEls[i].remove();
          } catch(e) {}
        }
      }

      window.switchToLanguage = function(lang) {
        var data;
        if (lang === 'original') {
          data = window.ASAPS_CONFIG.storyData;
          document.documentElement.setAttribute('dir', 'ltr');
        } else {
          var entry = window.ASAPS_TRANSLATIONS[lang];
          if (!entry) return;
          data = entry.data;
          document.documentElement.setAttribute('dir', entry.direction || 'ltr');
        }

        // Destroy previous player (stops audio, unmounts React)
        destroyCurrentPlayer();

        var storySource = 'data:application/zip;base64,' + data;
        var playerEl = document.getElementById('player');
        playerEl.innerHTML = '<div class="loading-screen"><div class="spinner"></div><div>Loading story...</div></div>';

        // Determine mobile mode: cover only when explicitly chosen
        var mobileScaling = window.ASAPS_CONFIG.mobileScalingMode || 'auto';
        var mobileMode = (mobileScaling === 'cover') && !!window.ASAPS_MOBILE;
        var effectiveFontScale = ((mobileScaling === 'auto' || mobileScaling === 'cover') && window.ASAPS_MOBILE)
          ? window.ASAPS_CONFIG.mobileFontScale : 1.0;

        if (typeof ASAPSPlayer !== 'undefined') {
          window._asapsPlayerInstance = ASAPSPlayer.init('#player', {
            story: storySource,
            enableAI: window.ASAPS_CONFIG.enableAI,
            mobileMode: mobileMode,
            mobileFontScale: effectiveFontScale,
          });
        }
      };
    })();
  </script>

  {{PLAYER_SCRIPT}}

  <script>
    (function() {
      if (window.parent !== window) {
        document.body.classList.add('iframe-mode');
      }
      // Determine mobile mode: cover only when explicitly chosen
      var mobileScaling = window.ASAPS_CONFIG.mobileScalingMode || 'auto';
      var mobileMode = (mobileScaling === 'cover') && !!window.ASAPS_MOBILE;
      var effectiveFontScale = ((mobileScaling === 'auto' || mobileScaling === 'cover') && window.ASAPS_MOBILE)
        ? window.ASAPS_CONFIG.mobileFontScale : 1.0;

      var storySource = 'data:application/zip;base64,' + window.ASAPS_CONFIG.storyData;
      if (typeof ASAPSPlayer !== 'undefined') {
        window._asapsPlayerInstance = ASAPSPlayer.init('#player', {
          story: storySource,
          enableAI: window.ASAPS_CONFIG.enableAI,
          mobileMode: mobileMode,
          mobileFontScale: effectiveFontScale,
        });
      }
    })();
  </script>
</body>
</html>`;

// AI on-the-fly translation section (embedded in template when enabled)
const AI_TRANSLATION_SECTION = `<div class="ai-section">
      <div class="ai-row">
        <input type="text" id="ai-lang-input" class="ai-input" placeholder="Type any language..." />
        <button id="ai-translate-btn" class="ai-btn" onclick="ASAPS_AI_TRANSLATE.start()">Translate</button>
      </div>
      <div class="ai-disclaimer">AI translation — experimental, requires internet</div>
      <div id="ai-progress" class="ai-progress" style="display:none;"></div>
      <div id="ai-error" class="ai-error" style="display:none;"></div>
    </div>

  <!-- JSZip for AI translation (internet required anyway) -->
  <script src="https://cdn.jsdelivr.net/npm/jszip@3/dist/jszip.min.js"></script>

  <script>
    // --- AI On-the-Fly Translation ---
    window.ASAPS_AI_TRANSLATE = (function() {
      var cache = {};
      var BATCH_SIZE = 80;

      function show(id, text) {
        var el = document.getElementById(id);
        el.textContent = text;
        el.style.display = 'block';
      }
      function hide(id) { document.getElementById(id).style.display = 'none'; }

      // Simplified string extraction from project JSON
      function extractStrings(project) {
        var strings = {};
        var story = project.project && project.project.story;
        if (!story) return strings;
        var P = 'project.story';

        if (story.metadata && story.metadata.title) strings[P + '.metadata.title'] = story.metadata.title;

        // Characters
        if (Array.isArray(story.characters)) {
          for (var i = 0; i < story.characters.length; i++) {
            var ch = story.characters[i];
            if (ch.name) strings[P + '.characters.' + i + '.name'] = ch.name;
          }
        }

        // Beats
        if (Array.isArray(story.beats)) {
          for (var i = 0; i < story.beats.length; i++) {
            var beat = story.beats[i];
            var params = beat.parameters || beat;
            var prefix = P + '.beats.' + i;
            var fields = ['text', 'buttonText', 'prompt', 'question', 'message', 'title', 'author',
                          'restartText', 'creditsText', 'creditsPageTitle', 'creditsPageBody', 'creditsCloseText',
                          'placeholder', 'clearButtonText', 'fallbackText',
                          'npcName', 'displayTemplate', 'errorMessage'];
            for (var f = 0; f < fields.length; f++) {
              if (params[fields[f]] && typeof params[fields[f]] === 'string') {
                strings[prefix + '.parameters.' + fields[f]] = params[fields[f]];
              }
            }
            // Text variations
            if (Array.isArray(params.textVariations)) {
              for (var j = 0; j < params.textVariations.length; j++) {
                if (typeof params.textVariations[j] === 'string') {
                  strings[prefix + '.parameters.textVariations.' + j] = params.textVariations[j];
                }
              }
            }
            // Dialog tree
            if (params.dialogTree) {
              walkDialogNode(params.dialogTree, prefix + '.parameters.dialogTree', strings);
            }
            // Movement choices
            if (Array.isArray(params.choices)) {
              for (var j = 0; j < params.choices.length; j++) {
                var label = params.choices[j].displayText || params.choices[j].text || params.choices[j].location;
                if (label) strings[prefix + '.parameters.choices.' + j + '.displayText'] = label;
              }
            }
            // PickProp
            if (beat.type === 'pickProp' && Array.isArray(params.props)) {
              for (var j = 0; j < params.props.length; j++) {
                var propLabel = params.props[j].displayName || params.props[j].name;
                if (propLabel) strings[prefix + '.parameters.props.' + j + '.displayName'] = propLabel;
                if (params.props[j].description) strings[prefix + '.parameters.props.' + j + '.description'] = params.props[j].description;
              }
            }
            // Hyperlinks
            if (Array.isArray(params.hyperlinks)) {
              for (var j = 0; j < params.hyperlinks.length; j++) {
                if (params.hyperlinks[j].word) strings[prefix + '.parameters.hyperlinks.' + j + '.word'] = params.hyperlinks[j].word;
              }
            }
          }
        }
        return strings;
      }

      function walkDialogNode(node, path, strings) {
        if (!node) return;
        if (node.speaker) strings[path + '.speaker'] = node.speaker;
        if (node.text) strings[path + '.text'] = node.text;
        if (Array.isArray(node.choices)) {
          for (var i = 0; i < node.choices.length; i++) {
            if (node.choices[i].text) strings[path + '.choices.' + i + '.text'] = node.choices[i].text;
            if (node.choices[i].dialogNode) walkDialogNode(node.choices[i].dialogNode, path + '.choices.' + i + '.dialogNode', strings);
          }
        }
      }

      // Apply translations to a deep clone
      function applyTranslations(projectData, translations) {
        var clone = JSON.parse(JSON.stringify(projectData));
        for (var path in translations) {
          setNested(clone, path, translations[path]);
        }
        return clone;
      }

      function setNested(obj, path, value) {
        var parts = path.split('.');
        var current = obj;
        for (var i = 0; i < parts.length - 1; i++) {
          var key = parts[i];
          var idx = Number(key);
          if (!isNaN(idx) && Array.isArray(current)) current = current[idx];
          else current = current && current[key];
          if (current == null) return;
        }
        var last = parts[parts.length - 1];
        var lastIdx = Number(last);
        if (!isNaN(lastIdx) && Array.isArray(current)) current[lastIdx] = value;
        else if (current && typeof current === 'object') current[last] = value;
      }

      // AI API call
      async function callAI(systemPrompt, userMessage, config) {
        if (config.provider === 'anthropic') {
          var base = (config.baseUrl || 'https://api.anthropic.com').replace(/\\/+$/, '');
          var url = base.endsWith('/v1') ? base + '/messages' : base + '/v1/messages';
          var resp = await fetch(url, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'x-api-key': config.apiKey,
              'anthropic-version': '2023-06-01',
              'anthropic-dangerous-direct-browser-access': 'true',
            },
            body: JSON.stringify({
              model: config.model || 'claude-sonnet-4-20250514',
              max_tokens: 8192,
              system: systemPrompt,
              messages: [{ role: 'user', content: userMessage }],
            }),
          });
          if (!resp.ok) throw new Error('Anthropic API error ' + resp.status);
          var data = await resp.json();
          return (data.content && data.content[0] && data.content[0].text) || '';
        } else {
          var url;
          if (config.baseUrl) url = config.baseUrl.replace(/\\/$/, '') + '/chat/completions';
          else url = 'https://api.openai.com/v1/chat/completions';
          var headers = { 'Content-Type': 'application/json' };
          if (config.apiKey) headers['Authorization'] = 'Bearer ' + config.apiKey;
          var resp = await fetch(url, {
            method: 'POST',
            headers: headers,
            body: JSON.stringify({
              model: config.model || 'gpt-4o-mini',
              messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: userMessage },
              ],
              temperature: 0.3,
              response_format: { type: 'json_object' },
            }),
          });
          if (!resp.ok) throw new Error('AI API error ' + resp.status);
          var data = await resp.json();
          return (data.choices && data.choices[0] && data.choices[0].message && data.choices[0].message.content) || '';
        }
      }

      // Detect non-Latin scripts and load fonts from Google CDN
      function loadFontsForText(text) {
        var RANGES = [
          [0x0600, 0x06FF, 'Noto Sans Arabic'], [0x0750, 0x077F, 'Noto Sans Arabic'], [0x08A0, 0x08FF, 'Noto Sans Arabic'],
          [0x0590, 0x05FF, 'Noto Sans Hebrew'], [0x0900, 0x097F, 'Noto Sans Devanagari'], [0x0980, 0x09FF, 'Noto Sans Bengali'],
          [0x0B80, 0x0BFF, 'Noto Sans Tamil'], [0x0C00, 0x0C7F, 'Noto Sans Telugu'], [0x0E00, 0x0E7F, 'Noto Sans Thai'],
          [0x10A0, 0x10FF, 'Noto Sans Georgian'], [0x1780, 0x17FF, 'Noto Sans Khmer'], [0x1000, 0x109F, 'Noto Sans Myanmar'],
          [0xAC00, 0xD7AF, 'Noto Sans KR'], [0x4E00, 0x9FFF, 'Noto Sans SC'],
          [0x3040, 0x309F, 'Noto Sans JP'], [0x30A0, 0x30FF, 'Noto Sans JP'],
        ];
        var fonts = {};
        for (var i = 0; i < text.length; i++) {
          var cp = text.codePointAt(i);
          if (cp < 0x0530) continue;
          for (var r = 0; r < RANGES.length; r++) {
            if (cp >= RANGES[r][0] && cp <= RANGES[r][1]) { fonts[RANGES[r][2]] = true; break; }
          }
          if (cp > 0xFFFF) i++;
        }
        var names = Object.keys(fonts);
        if (names.length === 0) return;
        var families = names.map(function(f) { return 'family=' + encodeURIComponent(f) + ':wght@400;700'; }).join('&');
        var url = 'https://fonts.googleapis.com/css2?' + families + '&display=swap';
        if (!document.querySelector('link[href="' + url + '"]')) {
          var link = document.createElement('link');
          link.rel = 'stylesheet';
          link.href = url;
          document.head.appendChild(link);
        }
      }

      // Check if language is RTL
      function isRTL(langName) {
        var lower = langName.toLowerCase();
        var rtlNames = ['arabic', 'hebrew', 'persian', 'farsi', 'urdu', 'pashto', 'yiddish', 'sindhi', 'dhivehi', 'kurdish', 'uyghur'];
        for (var i = 0; i < rtlNames.length; i++) {
          if (lower.indexOf(rtlNames[i]) >= 0) return true;
        }
        return false;
      }

      return {
        cache: cache,

        start: async function() {
          var langInput = document.getElementById('ai-lang-input');
          var language = langInput.value.trim();
          if (!language) return;

          var config = window.ASAPS_CONFIG.aiConfig;
          if (!config) {
            show('ai-error', 'No AI configuration available');
            return;
          }

          hide('ai-error');

          // Check cache
          if (cache[language]) {
            show('ai-progress', 'Loading cached translation...');
            // Add as option and switch
            addAndSwitch(language, cache[language].data, cache[language].direction);
            hide('ai-progress');
            return;
          }

          if (typeof JSZip === 'undefined') {
            show('ai-error', 'JSZip not loaded — check internet connection');
            return;
          }

          var btn = document.getElementById('ai-translate-btn');
          btn.disabled = true;
          show('ai-progress', 'Parsing story...');

          try {
            // Parse original ZIP to get project.json
            var zipData = Uint8Array.from(atob(window.ASAPS_CONFIG.storyData), function(c) { return c.charCodeAt(0); });
            var zip = await JSZip.loadAsync(zipData);
            var projectJson = await zip.file('project.json').async('string');
            var projectData = JSON.parse(projectJson);

            // Extract strings
            var strings = extractStrings(projectData);
            var keys = Object.keys(strings);
            if (keys.length === 0) {
              show('ai-error', 'No translatable strings found');
              btn.disabled = false;
              hide('ai-progress');
              return;
            }

            // Batch translate
            var allTranslations = {};
            var translated = 0;
            for (var i = 0; i < keys.length; i += BATCH_SIZE) {
              var batchKeys = keys.slice(i, i + BATCH_SIZE);
              var batch = {};
              for (var j = 0; j < batchKeys.length; j++) batch[batchKeys[j]] = strings[batchKeys[j]];

              show('ai-progress', 'Translating: ' + translated + '/' + keys.length + ' strings...');

              var sysPrompt = 'Translate the following JSON values to ' + language + '. Keep keys unchanged. Return ONLY valid JSON. Preserve any {{variables}} or HTML tags.';
              var response = await callAI(sysPrompt, JSON.stringify(batch, null, 2), config);

              // Parse response
              var cleaned = response.trim();
              var fence = String.fromCharCode(96,96,96);
              if (cleaned.indexOf(fence) === 0) {
                var firstNl = cleaned.indexOf('\\n');
                if (firstNl > 0) cleaned = cleaned.substring(firstNl + 1);
                var lastFence = cleaned.lastIndexOf(fence);
                if (lastFence > 0) cleaned = cleaned.substring(0, lastFence).trim();
              }
              var parsed = JSON.parse(cleaned);
              for (var k in batch) {
                allTranslations[k] = typeof parsed[k] === 'string' ? parsed[k] : batch[k];
              }
              translated += batchKeys.length;
            }

            show('ai-progress', 'Applying translations...');

            // Apply and repackage
            var translatedProject = applyTranslations(projectData, allTranslations);
            var newZip = new JSZip();
            for (var path in zip.files) {
              if (path === 'project.json') continue;
              var f = zip.files[path];
              if (f.dir) newZip.folder(path);
              else newZip.file(path, await f.async('arraybuffer'));
            }
            newZip.file('project.json', JSON.stringify(translatedProject, null, 2));
            var blob = await newZip.generateAsync({ type: 'arraybuffer' });

            // Convert to base64
            var bytes = new Uint8Array(blob);
            var binary = '';
            for (var i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
            var base64 = btoa(binary);

            var direction = isRTL(language) ? 'rtl' : 'ltr';

            // Cache
            cache[language] = { data: base64, direction: direction };

            // Load fonts for translated text
            var allText = Object.values(allTranslations).join(' ');
            loadFontsForText(allText);

            // Add to selector and switch
            addAndSwitch(language, base64, direction);

            show('ai-progress', 'Done! Translated ' + keys.length + ' strings.');
            setTimeout(function() { hide('ai-progress'); }, 3000);
          } catch (e) {
            console.error('[AI Translate]', e);
            show('ai-error', 'Translation failed: ' + (e.message || e));
            hide('ai-progress');
          } finally {
            btn.disabled = false;
          }
        }
      };

      function addAndSwitch(language, base64, direction) {
        // Add to ASAPS_TRANSLATIONS
        window.ASAPS_TRANSLATIONS[language] = { name: language, data: base64, direction: direction };

        // Add to select if not already there
        var select = document.getElementById('lang-select');
        var exists = false;
        for (var i = 0; i < select.options.length; i++) {
          if (select.options[i].value === language) { exists = true; break; }
        }
        if (!exists) {
          var opt = document.createElement('option');
          opt.value = language;
          opt.textContent = language + ' (AI)';
          select.appendChild(opt);
        }
        select.value = language;
        window.switchToLanguage(language);
      }
    })();
  </script>`;

export interface HtmlExportOptions {
  /** Export mode: 'folder' creates separate files, 'single-file' inlines everything */
  mode: 'folder' | 'single-file';
  /** Enable responsive scaling to container */
  responsive: boolean;
  /** Enable AI features (requires API key on playback) */
  enableAI: boolean;
  /** Show API key prompt when AI is needed */
  showApiKeyPrompt: boolean;
  /** AI provider to use (if embedding API key) */
  aiProvider?: AIProvider;
  /** API key to embed (if provided by creator) */
  aiApiKey?: string;
  /** Custom base URL for API (OpenAI-compatible endpoints) */
  aiBaseUrl?: string;
  /** Model override (e.g., 'gpt-5.2', 'claude-sonnet-4-20250514') */
  aiModel?: string;
  /** TTS provider type */
  ttsProvider?: string;
  /** TTS API key to embed */
  ttsApiKey?: string;
  /** TTS model */
  ttsModel?: string;
  /** TTS base URL (for custom providers) */
  ttsBaseUrl?: string;
  /** Speaker → voice ID mapping */
  ttsSpeakerVoices?: Record<string, string>;
  /** Default voice ID */
  ttsDefaultVoiceId?: string;
  /** Pre-made translations to bundle with the export */
  existingTranslations?: TranslationResource[];
  /** Enable AI on-the-fly translation in the exported player */
  enableAIOnTheFly?: boolean;
}

export interface HtmlExportResult {
  /** For single-file mode: the complete HTML as a string */
  html?: string;
  /** For folder mode: a Blob containing the ZIP of all files */
  zip?: Blob;
  /** Export mode used */
  mode: 'folder' | 'single-file';
}

/**
 * Export project as standalone HTML
 */
export async function exportAsHtml(
  projectId: string,
  options: HtmlExportOptions
): Promise<HtmlExportResult> {
  const storage = getStorageManager();

  // Get project data
  const projectResult = await storage.getProject(projectId);
  if (!projectResult.success || !projectResult.data) {
    throw new Error('Project not found');
  }

  const project = projectResult.data;

  // First, export the project as a playable .asaps.zip
  const storyZipBlob = await createStoryZip(projectId);

  if (options.mode === 'single-file') {
    return exportAsSingleFile(project, storyZipBlob, options);
  } else {
    return exportAsFolder(project, storyZipBlob, options);
  }
}

/**
 * Create story ZIP blob for export (same format as regular export)
 */
async function createStoryZip(projectId: string): Promise<Blob> {
  const { exportProjectAsZip } = await import('../utils/projectZipManager');
  return exportProjectAsZip(projectId);
}

/**
 * Create a story ZIP from in-memory project data (for translated stories).
 * Re-packages the original ZIP but replaces project.json with translated data.
 */
async function createStoryZipFromData(originalZipBlob: Blob, translatedProjectData: any): Promise<Blob> {
  const originalZip = await JSZip.loadAsync(originalZipBlob);

  // Create new ZIP with same structure
  const newZip = new JSZip();

  // Copy all files from original except project.json
  for (const [path, file] of Object.entries(originalZip.files)) {
    if (path === 'project.json') continue;
    if (file.dir) {
      newZip.folder(path);
    } else {
      const content = await file.async('arraybuffer');
      newZip.file(path, content);
    }
  }

  // Add translated project.json
  newZip.file('project.json', JSON.stringify(translatedProjectData, null, 2));

  return newZip.generateAsync({ type: 'blob' });
}

/**
 * Export as a single self-contained HTML file
 */
async function exportAsSingleFile(
  project: any,
  storyZipBlob: Blob,
  options: HtmlExportOptions
): Promise<HtmlExportResult> {
  // Convert story to base64
  const storyArrayBuffer = await storyZipBlob.arrayBuffer();
  const storyBase64 = arrayBufferToBase64(storyArrayBuffer);

  // Get player bundle (would normally be loaded from player-web package)
  // For now, use a placeholder that indicates the player bundle should be included
  const playerScript = await getPlayerScript();

  // Build AI config object (or null if not provided)
  const aiConfig = options.aiProvider && options.aiApiKey
    ? JSON.stringify({
        provider: options.aiProvider,
        apiKey: options.aiApiKey,
        baseUrl: options.aiBaseUrl || undefined,
        model: options.aiModel || undefined,
      })
    : 'null';

  // Build TTS config object (or null if not provided)
  const ttsConfig = options.ttsProvider && options.ttsProvider !== 'web-speech'
    ? JSON.stringify({
        provider: options.ttsProvider,
        apiKey: options.ttsApiKey || undefined,
        model: options.ttsModel || undefined,
        baseUrl: options.ttsBaseUrl || undefined,
        speakerVoices: options.ttsSpeakerVoices || undefined,
        defaultVoiceId: options.ttsDefaultVoiceId || undefined,
      })
    : options.ttsProvider === 'web-speech'
      ? JSON.stringify({ provider: 'web-speech' })
      : 'null';

  // Get mobile settings from project
  const mobileScalingMode = project.globalSettings?.project?.mobileScalingMode || 'auto';
  const mobileFontScale = project.globalSettings?.project?.mobileFontScale || 1.0;

  // Build HTML
  const html = HTML_TEMPLATE
    .replace('{{STORY_TITLE}}', escapeHtml(project.name || 'ASAPS Story'))
    .replace('{{STORY_AUTHOR}}', escapeHtml(getAuthor(project)))
    .replace('{{ENABLE_AI}}', String(options.enableAI))
    .replace("'{{STORY_URL}}'", "''")  // Empty for single-file mode
    .replace("'{{STORY_DATA}}'", `'${storyBase64}'`)
    .replace('{{AI_CONFIG}}', aiConfig)
    .replace('{{TTS_CONFIG}}', ttsConfig)
    .replace('{{MOBILE_SCALING_MODE}}', mobileScalingMode)
    .replace('{{MOBILE_FONT_SCALE}}', String(mobileFontScale))
    .replace('{{PLAYER_SCRIPT}}', playerScript);

  return { html, mode: 'single-file' };
}

/**
 * Export as a folder with separate files
 */
async function exportAsFolder(
  project: any,
  storyZipBlob: Blob,
  options: HtmlExportOptions
): Promise<HtmlExportResult> {
  const zip = new JSZip();

  // Get player bundle
  const playerScript = await getPlayerScript();

  // Build AI config object (or null if not provided)
  const aiConfig = options.aiProvider && options.aiApiKey
    ? JSON.stringify({
        provider: options.aiProvider,
        apiKey: options.aiApiKey,
        baseUrl: options.aiBaseUrl || undefined,
        model: options.aiModel || undefined,
      })
    : 'null';

  // Get mobile settings from project
  const mobileScalingMode = project.globalSettings?.project?.mobileScalingMode || 'auto';
  const mobileFontScale = project.globalSettings?.project?.mobileFontScale || 1.0;

  // Build HTML that references external story file
  const html = HTML_TEMPLATE
    .replace('{{STORY_TITLE}}', escapeHtml(project.name || 'ASAPS Story'))
    .replace('{{STORY_AUTHOR}}', escapeHtml(getAuthor(project)))
    .replace('{{ENABLE_AI}}', String(options.enableAI))
    .replace("'{{STORY_URL}}'", "'story.asaps.zip'")
    .replace("'{{STORY_DATA}}'", "''")  // Empty for folder mode
    .replace('{{AI_CONFIG}}', aiConfig)
    .replace('{{MOBILE_SCALING_MODE}}', mobileScalingMode)
    .replace('{{MOBILE_FONT_SCALE}}', String(mobileFontScale))
    .replace('{{PLAYER_SCRIPT}}', playerScript);

  // Add files to ZIP
  zip.file('index.html', html);
  zip.file('story.asaps.zip', storyZipBlob);

  // Generate ZIP
  const zipBlob = await zip.generateAsync({ type: 'blob' });

  return { zip: zipBlob, mode: 'folder' };
}

/**
 * Get the player script and CSS bundle
 * Loads the pre-built player-web bundle from public folder
 * Uses base64 data URL to avoid any HTML escaping issues
 */
async function getPlayerScript(): Promise<string> {
  // Try multiple paths to load the player bundle
  const jsPaths = [
    '/player-web.js',      // Development (Vite dev server)
    './player-web.js',     // Relative path
    'player-web.js',       // Same folder
  ];

  const cssPaths = [
    '/player-web.css',      // Development (Vite dev server)
    './player-web.css',     // Relative path
    'player-web.css',       // Same folder
  ];

  let scriptTag = '';
  let styleTag = '';

  // Load JavaScript bundle
  for (const path of jsPaths) {
    try {
      const response = await fetch(path);
      if (response.ok) {
        const script = await response.text();
        console.log('[HtmlExporter] Loaded player bundle from:', path, 'size:', script.length);

        // Encode as base64 data URL to avoid any HTML escaping issues
        const base64Script = btoa(unescape(encodeURIComponent(script)));
        scriptTag = `<script src="data:text/javascript;base64,${base64Script}"></script>`;
        break;
      }
    } catch (e) {
      // Try next path
    }
  }

  // Load CSS bundle
  for (const path of cssPaths) {
    try {
      const response = await fetch(path);
      if (response.ok) {
        const css = await response.text();
        console.log('[HtmlExporter] Loaded player CSS from:', path, 'size:', css.length);

        // Encode as base64 data URL to avoid any HTML escaping issues
        const base64Css = btoa(unescape(encodeURIComponent(css)));
        styleTag = `<link rel="stylesheet" href="data:text/css;base64,${base64Css}">`;
        break;
      }
    } catch (e) {
      // Try next path
    }
  }

  if (scriptTag) {
    return `${styleTag}\n  ${scriptTag}`;
  }

  console.error('[HtmlExporter] Could not load player-web bundle from any path');

  // Fallback: Show error with instructions
  return `<script>
// ASAPS Player Web - Bundle not found
(function() {
  window.ASAPSPlayer = {
    init: function(container, options) {
      var el = typeof container === 'string' ? document.querySelector(container) : container;
      if (!el) return;
      el.innerHTML = '<div style="display:flex;align-items:center;justify-content:center;height:100%;color:#fff;text-align:center;padding:20px;font-family:system-ui,sans-serif;">' +
        '<div>' +
        '<div style="width:64px;height:64px;background:#ff6b6b;color:white;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:32px;font-weight:bold;margin:0 auto 20px;">!</div>' +
        '<h2 style="margin-bottom:16px;">Player Bundle Missing</h2>' +
        '<p style="color:#888;margin-bottom:16px;max-width:400px;">The player-web bundle was not found. This is likely a build issue.</p>' +
        '<p style="color:#666;font-size:14px;">Run: npm run build -w @asaps/player-web</p>' +
        '</div></div>';
    }
  };
})();
</script>`;
}

/**
 * Helper: Convert ArrayBuffer to base64
 */
function arrayBufferToBase64(buffer: ArrayBuffer): string {
  let binary = '';
  const bytes = new Uint8Array(buffer);
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

/**
 * Helper: Escape HTML special characters
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Helper: Get author from project
 */
function getAuthor(project: any): string {
  if (project.story?.metadata?.author) {
    return project.story.metadata.author;
  }
  if (project.globalSettings?.author) {
    return project.globalSettings.author;
  }
  return 'ASAPS Creator';
}

/** RTL language codes for embedding in the template */
const RTL_LANGUAGE_CODES = ['ar','he','fa','ur','ps','yi','sd','dv','ku','ug','arc','syc','nqo'];

/**
 * Download HTML export to user's computer
 */
export async function downloadHtmlExport(
  projectId: string,
  projectName: string,
  options: HtmlExportOptions
): Promise<void> {
  const safeName = projectName.replace(/[^a-z0-9]/gi, '_');
  const hasExistingTranslations = options.existingTranslations && options.existingTranslations.length > 0;
  const hasAIOnTheFly = options.enableAIOnTheFly && options.aiProvider && (options.aiApiKey || options.aiProvider === 'local');

  if (!hasExistingTranslations && !hasAIOnTheFly) {
    // Standard export (no translations, no AI on-the-fly)
    const result = await exportAsHtml(projectId, options);
    if (result.mode === 'single-file' && result.html) {
      const blob = new Blob([result.html], { type: 'text/html' });
      downloadBlob(blob, `${safeName}.html`);
    } else if (result.mode === 'folder' && result.zip) {
      downloadBlob(result.zip, `${safeName}_html.zip`);
    }
    return;
  }

  // Enhanced multi-language export
  console.log('[HtmlExporter] Starting enhanced multi-language export');

  const { getProjectDataForExport, exportProjectAsZip } = await import('../utils/projectZipManager');

  // Get original story data
  const originalZipBlob = await exportProjectAsZip(projectId);
  const originalBase64 = arrayBufferToBase64(await originalZipBlob.arrayBuffer());

  // Process pre-made translations
  const translationEntries: Array<{
    languageCode: string;
    languageName: string;
    direction: string;
    base64: string;
    requiredFonts: string[];
  }> = [];

  if (hasExistingTranslations) {
    const projectData = await getProjectDataForExport(projectId);

    for (const resource of options.existingTranslations!) {
      console.log(`[HtmlExporter] Processing translation: ${resource.languageName} (${resource.languageCode})`);

      // Apply the translation to get translated project data
      const translatedData = applyTranslationResource(projectData, resource);

      // Create translated ZIP
      const translatedZip = await createStoryZipFromData(originalZipBlob, translatedData);
      const translatedBase64 = arrayBufferToBase64(await translatedZip.arrayBuffer());

      translationEntries.push({
        languageCode: resource.languageCode,
        languageName: resource.languageName,
        direction: resource.direction,
        base64: translatedBase64,
        requiredFonts: resource.requiredFonts || [],
      });

      console.log(`[HtmlExporter] ${resource.languageName} ZIP: ${translatedZip.size} bytes`);
    }
  }

  // Collect required fonts and inline them
  const allFonts = new Set<string>();
  for (const entry of translationEntries) {
    for (const font of entry.requiredFonts) {
      allFonts.add(font);
    }
  }

  let embeddedFontsCss = '';
  if (allFonts.size > 0) {
    console.log(`[HtmlExporter] Downloading and inlining fonts: ${Array.from(allFonts).join(', ')}`);
    const fontCss = await downloadAndInlineFonts(Array.from(allFonts));
    if (fontCss) {
      embeddedFontsCss = `<style>\n/* Bundled Noto fonts for offline rendering */\n${fontCss}\n  </style>`;
    }
  }

  // Build template data
  const storage = getStorageManager();
  const projectResult = await storage.getProject(projectId);
  const project = projectResult.data!;

  const playerScript = await getPlayerScript();

  const aiConfig = options.aiProvider && options.aiApiKey
    ? JSON.stringify({
        provider: options.aiProvider,
        apiKey: options.aiApiKey,
        baseUrl: options.aiBaseUrl || undefined,
        model: options.aiModel || undefined,
      })
    : 'null';

  // Build language options HTML
  const languageOptionsHtml = translationEntries
    .map(t => `<option value="${escapeHtml(t.languageCode)}">${escapeHtml(t.languageName)}</option>`)
    .join('\n        ');

  // Build translations map JavaScript
  const translationsMapJs = translationEntries
    .map(t => `      ${JSON.stringify(t.languageCode)}: { name: ${JSON.stringify(t.languageName)}, data: '${t.base64}', direction: '${t.direction}' }`)
    .join(',\n');

  // Build AI section (or empty)
  const aiSectionHtml = hasAIOnTheFly ? AI_TRANSLATION_SECTION : '';

  // Build TTS config object
  const ttsConfig = options.ttsProvider && options.ttsProvider !== 'web-speech'
    ? JSON.stringify({
        provider: options.ttsProvider,
        apiKey: options.ttsApiKey || undefined,
        model: options.ttsModel || undefined,
        baseUrl: options.ttsBaseUrl || undefined,
        speakerVoices: options.ttsSpeakerVoices || undefined,
        defaultVoiceId: options.ttsDefaultVoiceId || undefined,
      })
    : options.ttsProvider === 'web-speech'
      ? JSON.stringify({ provider: 'web-speech' })
      : 'null';

  // Get mobile settings from project
  const mobileScalingMode = project.globalSettings?.project?.mobileScalingMode || 'auto';
  const mobileFontScale = project.globalSettings?.project?.mobileFontScale || 1.0;

  // Assemble the enhanced HTML
  const html = ENHANCED_MULTI_LANGUAGE_TEMPLATE
    .replace('{{STORY_TITLE}}', escapeHtml(project.name || 'ASAPS Story'))
    .replace('{{STORY_AUTHOR}}', escapeHtml(getAuthor(project)))
    .replace('{{EMBEDDED_FONTS}}', embeddedFontsCss)
    .replace('{{ENABLE_AI}}', String(options.enableAI))
    .replace("'{{ORIGINAL_STORY_DATA}}'", `'${originalBase64}'`)
    .replace('{{AI_CONFIG}}', aiConfig)
    .replace('{{TTS_CONFIG}}', ttsConfig)
    .replace('{{MOBILE_SCALING_MODE}}', mobileScalingMode)
    .replace('{{MOBILE_FONT_SCALE}}', String(mobileFontScale))
    .replace('{{LANGUAGE_OPTIONS}}', languageOptionsHtml)
    .replace('{{AI_TRANSLATION_SECTION}}', aiSectionHtml)
    .replace('{{TRANSLATIONS_MAP}}', translationsMapJs)
    .replace('{{RTL_LANGUAGES}}', JSON.stringify(RTL_LANGUAGE_CODES))
    .replace('{{PLAYER_SCRIPT}}', playerScript);

  console.log(`[HtmlExporter] Enhanced HTML size: ${html.length} bytes`);

  if (options.mode === 'single-file') {
    const blob = new Blob([html], { type: 'text/html' });
    downloadBlob(blob, `${safeName}.html`);
  } else {
    // Folder mode: wrap in a ZIP with the HTML as index.html
    // Translations are embedded in the HTML itself (not as separate files)
    const zip = new JSZip();
    zip.file('index.html', html);
    zip.file('story.asaps.zip', originalZipBlob);
    const zipBlob = await zip.generateAsync({ type: 'blob' });
    downloadBlob(zipBlob, `${safeName}_html.zip`);
  }

  console.log('[HtmlExporter] Enhanced export complete!');
}

/**
 * Helper: Download blob as file
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
