/**
 * relayKit — the "hide your API key" deployment story for exported HTML.
 *
 * An exported story with AI beats needs credentials at play time. Embedding
 * the author's key in the HTML means anyone can scrape it from a public
 * deployment. The relay kit is the alternative: a tiny serverless function
 * the author deploys NEXT TO the story (Netlify Drop understands the
 * netlify/functions/ folder convention out of the box). The player POSTs
 * { provider, body } to the same-origin function; the function injects the
 * key from the site's environment variables and forwards to the FIXED
 * official endpoint. The key never travels to the browser.
 *
 * Contract (mirrored by @asaps/core createRelayTransport):
 *   POST { provider: 'anthropic' | 'openai', body: <provider request body> }
 *   → provider-shaped JSON, status passed through.
 *
 * Security posture (documented in the generated README):
 *   - Upstream URLs are HARDCODED — the client cannot redirect the relay.
 *   - No CORS headers are emitted, so browsers only allow same-origin
 *     calls: the key is only spendable from the site it's deployed on.
 *   - The key lives in Netlify env vars, never in the bundle.
 */

/** Default same-origin path where the Netlify function answers. */
export const DEFAULT_RELAY_PATH = '/.netlify/functions/asaps-ai';

/** Netlify Functions v2 (ESM, web Request/Response) relay source. */
export const RELAY_FUNCTION_SOURCE = `// ASAPS AI relay — generated by ASAPS Builder.
// Deploy next to your exported story; set ANTHROPIC_API_KEY and/or
// OPENAI_API_KEY in Project configuration → Environment variables.
// See README-RELAY.md for the 3-step walkthrough.

const UPSTREAMS = {
  anthropic: 'https://api.anthropic.com/v1/messages',
  openai: 'https://api.openai.com/v1/chat/completions',
};

export default async (req) => {
  if (req.method !== 'POST') {
    return Response.json({ error: 'POST only' }, { status: 405 });
  }

  let payload;
  try {
    payload = await req.json();
  } catch {
    return Response.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const { provider, body } = payload || {};
  if (!UPSTREAMS[provider] || !body || typeof body !== 'object') {
    return Response.json(
      { error: "Expected { provider: 'anthropic' | 'openai', body: {...} }" },
      { status: 400 },
    );
  }

  const key = provider === 'anthropic'
    ? process.env.ANTHROPIC_API_KEY
    : process.env.OPENAI_API_KEY;
  if (!key) {
    const name = provider === 'anthropic' ? 'ANTHROPIC_API_KEY' : 'OPENAI_API_KEY';
    return Response.json(
      { error: name + ' is not set. Add it under Project configuration → Environment variables, then redeploy.' },
      { status: 500 },
    );
  }

  const headers = provider === 'anthropic'
    ? {
        'content-type': 'application/json',
        'x-api-key': key,
        'anthropic-version': '2023-06-01',
      }
    : {
        'content-type': 'application/json',
        authorization: 'Bearer ' + key,
      };

  const upstream = await fetch(UPSTREAMS[provider], {
    method: 'POST',
    headers,
    body: JSON.stringify(body),
  });

  // Pass the provider-shaped JSON (and status) through untouched so the
  // player's response parsing is identical for direct and relayed calls.
  return new Response(await upstream.text(), {
    status: upstream.status,
    headers: { 'content-type': 'application/json' },
  });
};
`;

export const RELAY_README = `# ASAPS AI relay — deploy your story WITHOUT exposing your API key

Your exported story uses AI at play time. Instead of embedding your API key
in the HTML (where anyone can read it), this kit runs a tiny relay next to
your story. The key stays on the server; players never see it.

## Deploy in 3 steps (Netlify)

1. Put your exported story file(s) into THIS folder, next to the
   \`netlify/\` directory (rename your export to \`index.html\` if it isn't
   already). Then drag the WHOLE folder onto https://app.netlify.com/drop

2. In your new project: **Project configuration → Environment variables →
   Add a variable**. The form has more options than you need — this is all
   that matters:
   - **Key**: \`ANTHROPIC_API_KEY\` (Claude) or \`OPENAI_API_KEY\` (OpenAI) —
     exactly these names, all caps
   - **Secret**: check "Contains secret values" (recommended)
   - **Scopes**: leave "All scopes" (the relay runs under *Functions*, so
     if you pick specific scopes, Functions MUST stay checked)
   - **Values**: choose **"Same value for all deploy contexts"** and paste
     your key once — no need for per-context values
   Then **Create variable**.

3. Environment variables only apply to NEW deploys: go to **Deploys →
   Trigger deploy → Deploy project**. When it finishes, open the site —
   AI beats now work with no key in the page.

## How it stays safe

- The relay only ever forwards to the official Anthropic / OpenAI
  endpoints — a caller cannot point it anywhere else.
- It sends no CORS headers, so browsers only allow calls from YOUR site's
  own pages. Another website cannot spend your key through the relay.
- The key lives in Netlify's environment variables, not in any file.

## Notes

- Anyone who can play your story can, by playing it, make AI calls through
  the relay — that is the point. Watch your provider's usage dashboard and
  set spending limits there.
- Works on any host that supports Netlify-style functions. For other hosts
  (Cloudflare, Vercel), port \`netlify/functions/asaps-ai.mjs\` — it is
  ~60 lines of standard fetch code with no dependencies.
`;

export interface RelayKitFile {
  path: string;
  content: string;
}

/** The files the export writes for a relay deployment. */
export function buildRelayKitFiles(): RelayKitFile[] {
  return [
    { path: 'netlify/functions/asaps-ai.mjs', content: RELAY_FUNCTION_SOURCE },
    { path: 'README-RELAY.md', content: RELAY_README },
  ];
}
