/**
 * relayKit — the "hide your API key" deployment story for exported HTML.
 *
 * An exported story with AI beats needs credentials at play time. Embedding
 * the author's key in the HTML means anyone can scrape it from a public
 * deployment. The relay kit is the alternative: a tiny serverless function
 * the author deploys NEXT TO the story (Netlify Drop understands the
 * netlify/functions/ folder convention out of the box). The player POSTs
 * { provider, body } to the same-origin function; the function injects the
 * key from the site's environment variables and forwards to the FIXED
 * official endpoint. The key never travels to the browser.
 *
 * Contract (mirrored by @asaps/core createRelayTransport):
 *   POST { provider: 'anthropic' | 'openai', body: <provider request body> }
 *   → provider-shaped JSON, status passed through.
 *
 * Security posture (documented in the generated README):
 *   - Upstream URLs are HARDCODED — the client cannot redirect the relay.
 *   - No CORS headers are emitted, so browsers only allow same-origin
 *     calls: the key is only spendable from the site it's deployed on.
 *   - The key lives in Netlify env vars, never in the bundle.
 */

/** Default same-origin path where the Netlify function answers. */
export const DEFAULT_RELAY_PATH = '/.netlify/functions/asaps-ai';

/** Netlify Functions v2 (ESM, web Request/Response) relay source. */
export const RELAY_FUNCTION_SOURCE = `// ASAPS AI relay — generated by ASAPS Builder.
// Deploy next to your exported story (same-origin mode) OR as its own
// site shared by several stories (set ALLOWED_ORIGINS). Set
// ANTHROPIC_API_KEY and/or OPENAI_API_KEY in Project configuration →
// Environment variables. See README-RELAY.md for the walkthroughs.

const UPSTREAMS = {
  anthropic: 'https://api.anthropic.com/v1/messages',
  openai: 'https://api.openai.com/v1/chat/completions',
};

// Cross-origin access is opt-in via ALLOWED_ORIGINS (comma-separated).
// Entries are exact origins ("https://my-story.netlify.app") or
// suffix wildcards ("*.netlify.app" — any https site on that suffix).
// Unset ⇒ no CORS headers are emitted, so browsers only allow calls
// from THIS site's own pages (the co-located default).
function corsHeadersFor(req) {
  const raw = process.env.ALLOWED_ORIGINS;
  const origin = req.headers.get('origin');
  if (!raw || !origin) return null;
  let host;
  try {
    const u = new URL(origin);
    if (u.protocol !== 'https:' && u.hostname !== 'localhost') return null;
    host = u.hostname;
  } catch { return null; }
  const allowed = raw.split(',').map((e) => e.trim()).filter(Boolean).some((entry) => {
    if (entry.startsWith('*.')) return host.endsWith(entry.slice(1)); // ".netlify.app"
    try { return new URL(entry).origin === origin; } catch { return entry === origin; }
  });
  if (!allowed) return null;
  return {
    'access-control-allow-origin': origin,
    'access-control-allow-methods': 'POST, OPTIONS',
    'access-control-allow-headers': 'content-type',
    vary: 'Origin',
  };
}

export default async (req) => {
  const cors = corsHeadersFor(req);

  // Preflight for allowed cross-origin callers.
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: cors ? 204 : 403, headers: cors || {} });
  }

  if (req.method !== 'POST') {
    return Response.json({ error: 'POST only' }, { status: 405, headers: cors || {} });
  }

  let payload;
  try {
    payload = await req.json();
  } catch {
    return Response.json({ error: 'Invalid JSON body' }, { status: 400, headers: cors || {} });
  }

  const { provider, body } = payload || {};
  if (!UPSTREAMS[provider] || !body || typeof body !== 'object') {
    return Response.json(
      { error: "Expected { provider: 'anthropic' | 'openai', body: {...} }" },
      { status: 400, headers: cors || {} },
    );
  }

  const key = provider === 'anthropic'
    ? process.env.ANTHROPIC_API_KEY
    : process.env.OPENAI_API_KEY;
  if (!key) {
    const name = provider === 'anthropic' ? 'ANTHROPIC_API_KEY' : 'OPENAI_API_KEY';
    return Response.json(
      { error: name + ' is not set. Add it under Project configuration → Environment variables, then redeploy.' },
      { status: 500, headers: cors || {} },
    );
  }

  const headers = provider === 'anthropic'
    ? {
        'content-type': 'application/json',
        'x-api-key': key,
        'anthropic-version': '2023-06-01',
      }
    : {
        'content-type': 'application/json',
        authorization: 'Bearer ' + key,
      };

  const upstream = await fetch(UPSTREAMS[provider], {
    method: 'POST',
    headers,
    body: JSON.stringify(body),
  });

  // Streaming requests (body.stream === true) are PIPED through untouched.
  // This is what makes long generations (AI dialog trees) survive on
  // serverless hosts: buffered functions are killed at the execution cap
  // (Netlify: 10 s), while a streamed response starts within milliseconds
  // and may keep streaming for as long as the model generates. The player
  // reassembles the SSE back into the plain response shape.
  const upstreamType = upstream.headers.get('content-type') || '';
  if (body.stream === true && upstream.ok && upstreamType.includes('text/event-stream')) {
    return new Response(upstream.body, {
      status: upstream.status,
      headers: {
        'content-type': 'text/event-stream',
        'cache-control': 'no-cache',
        ...(cors || {}),
      },
    });
  }

  // Non-streaming: pass the provider-shaped JSON (and status) through
  // untouched so response parsing is identical for direct and relayed calls.
  return new Response(await upstream.text(), {
    status: upstream.status,
    headers: { 'content-type': 'application/json', ...(cors || {}) },
  });
};
`;

export const RELAY_README = `# ASAPS AI relay — deploy your story WITHOUT exposing your API key

Your exported story uses AI at play time. Instead of embedding your API key
in the HTML (where anyone can read it), this kit runs a tiny relay server
function. The key stays on the server; players never see it.

> **Why not just drag-and-drop?** Netlify Drop (app.netlify.com/drop)
> uploads static files only — it does NOT deploy the relay function, and
> the story then gets a 404 from \`/.netlify/functions/asaps-ai\`. Use
> path A or B below (both deploy the function), or path C to keep
> drag-and-drop for the story itself.

Your story is already in place: this folder came out of the export with
\`index.html\` (the story), the relay function, and this README together.

## Path A — all in the browser, no terminal (GitHub + Netlify)

1. Go to https://github.com/new (free account is fine), name the
   repository (e.g. \`my-story\`), leave it **Private** if you like →
   **Create repository**.
2. On the new repo page, click **uploading an existing file**, then drag
   the CONTENTS of this folder (index.html, netlify.toml, and the
   netlify folder) into the upload area → **Commit changes**.
3. Go to https://app.netlify.com → **Add new project → Import an
   existing project → GitHub** → pick your repository. Accept the
   defaults → **Deploy**. (Because this is a Git deploy, Netlify DOES
   bundle the function.)
4. Add your API key — see **"Setting the API key"** below — then
   **Deploys → Trigger deploy → Deploy project** once so the function
   picks it up. Done: open the site, AI beats work, no key in the page.

To update the story later: on GitHub use **Add file → Upload files** and
drag the new \`index.html\` over the old one → Commit. Netlify redeploys
automatically.

## Path B — terminal (Netlify CLI)

From this folder (requires Node.js):

    npx netlify-cli deploy --prod

First run: log in, choose **Create & configure a new project**, accept
the defaults. The output should list **asaps-ai** under "Functions".
Then set the key (below, or \`npx netlify-cli env:set ANTHROPIC_API_KEY
sk-...\`) and run the same deploy command once more.

## Path C — one shared relay, drag-and-drop stories (classrooms)

Deploy the relay ONCE as its own site (path A or B, no index.html
needed), and let every story site use it:

1. On the RELAY site, add an environment variable \`ALLOWED_ORIGINS\` —
   a comma-separated list of the story sites allowed to use it:
   - exact origins: \`https://annas-story.netlify.app,https://bens-story.netlify.app\`
   - or a suffix wildcard: \`*.netlify.app\` (careful: ANY Netlify site
     could then spend your key — prefer exact origins when you can)
2. Story authors export with **Use a relay** and put the relay's FULL
   URL in the Relay URL field:
   \`https://YOUR-RELAY-SITE.netlify.app/.netlify/functions/asaps-ai\`
3. Stories are plain static pages now — plain **drag-and-drop
   (Netlify Drop) works** for them. No functions, no keys, no terminal.

When a new story site joins, add its origin to \`ALLOWED_ORIGINS\` and
redeploy the relay.

## Setting the API key

**Project configuration → Environment variables → Add a variable.** The
form has more options than you need — this is all that matters:

- **Key**: \`ANTHROPIC_API_KEY\` (Claude) or \`OPENAI_API_KEY\` (OpenAI) —
  exactly these names, all caps
- **Secret**: check "Contains secret values" (recommended)
- **Scopes**: leave "All scopes" (the relay runs under *Functions*, so
  if you pick specific scopes, Functions MUST stay checked)
- **Values**: choose **"Same value for all deploy contexts"** and paste
  your key once

Then **Create variable** — and remember: variables only reach the
function on the NEXT deploy (**Deploys → Trigger deploy**).

## How it stays safe

- The relay only ever forwards to the official Anthropic / OpenAI
  endpoints — a caller cannot point it anywhere else.
- Without \`ALLOWED_ORIGINS\` it sends no CORS headers, so browsers only
  allow calls from the relay's own site. With \`ALLOWED_ORIGINS\`, only
  the origins YOU list can call it from a browser.
- The key lives in Netlify's environment variables, not in any file.

## Notes

- Anyone who can play your story can, by playing it, make AI calls
  through the relay — that is the point. Watch your provider's usage
  dashboard and set spending limits there.
- Works on any host that supports Netlify-style functions. For other
  hosts (Cloudflare, Vercel), port \`netlify/functions/asaps-ai.mjs\` —
  it is ~100 lines of standard fetch code with no dependencies.
`;

export const RELAY_NETLIFY_TOML = `[build]
  publish = "."

[functions]
  directory = "netlify/functions"
`;

export interface RelayKitFile {
  path: string;
  content: string;
}

/** The files the export writes for a relay deployment. */
export function buildRelayKitFiles(): RelayKitFile[] {
  return [
    { path: 'netlify/functions/asaps-ai.mjs', content: RELAY_FUNCTION_SOURCE },
    { path: 'netlify.toml', content: RELAY_NETLIFY_TOML },
    { path: 'README-RELAY.md', content: RELAY_README },
  ];
}
